In [1]:
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report, roc_auc_score
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
import seaborn as sns

from datetime import datetime
from dateutil.relativedelta import relativedelta


import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
df = pd.read_excel("../dataset/02.06.2025.xlsx")
df.head()

,App,Сумма выдачи,Дата выдачи,Дата погашения,Срок кредита (месяц),Статус кредита,Кредитный портфель#,Кредитный портфель вал.#,Портфель/Итог(%)#,Остаток стандарт#,...,Страна,Область \город,Регион \город,Село,Адрес месторождения,Семейное положение,Количество членов семьи,Образование,Место работы,Должность
0,C-00-30283,8000000.0,18.07.2018,17.07.2020,24.0,Списанный,3346360.8,0,0.0025,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,ФУРКАТ ТУМАНИ,NaN,NaN,NaN,1.0,Средне-специальное,Фуркат тумани Агросаноат ва транспорт кхк,хисобчи
1,C-00-30877,3000000.0,29.08.2018,05.08.2019,11.0,Списанный,824897.69,0,0.0006,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалиёт,ёрдамчи
2,C-00-31099,3000000.0,18.09.2018,18.09.2019,12.0,Списанный,622134.54,0,0.0004,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,КУКОН ШАХРИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалиёт,ёрдамчи
3,C-00-31145,3000000.0,20.09.2018,20.09.2019,12.0,Списанный,549419.14,0,0.0004,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,КУКОН ШАХРИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалиёт,шофёр
4,C-00-30609,3000000.0,13.08.2018,13.08.2019,12.0,Списанный,1722613.68,0,0.0012,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалиёт,нафакахур

In [3]:
df.columns = [col.lower() for col in df.columns]

In [4]:
df["кредитный продукт"].value_counts()

кредитный продукт
ISHONCH           7068
KAPITAL           3842
BARAKA             627
KAFOLAT            447
HAMKOR KAPITAL     142
Сармоя              85
Хамкор              54
Хазина              20
Хамкор Сармоя       14
Яхши ният            4
Мадор                4
Имкон                2
Name: count, dtype: int64

In [5]:
df_no_assets = df[df["кредитный продукт"] == 'ISHONCH']
df_no_assets.head()

,app,сумма выдачи,дата выдачи,дата погашения,срок кредита (месяц),статус кредита,кредитный портфель#,кредитный портфель вал.#,портфель/итог(%)#,остаток стандарт#,...,страна,область \город,регион \город,село,адрес месторождения,семейное положение,количество членов семьи,образование,место работы,должность
143,C-00-52877,5000000.0,11.08.2023,09.08.2024,12.0,Списанный,3746309.4,0,0.0028,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amalyot,уста
212,C-00-53282,5000000.0,05.09.2023,05.09.2024,12.0,Списанный,4580890.3,0,0.0034,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,ФУРКАТ ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amaliyot,уста
214,C-00-53012,4000000.0,18.08.2023,16.08.2024,12.0,Списанный,478947.03,0,0.0003,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,xususiy amaliyot,богбон
261,C-00-53277,5000000.0,04.09.2023,04.09.2024,12.0,Списанный,319060.65,0,0.0002,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,КУВА ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалийёт,Шифокор
282,C-00-53533,4000000.0,13.09.2023,13.09.2024,12.0,Списанный,2673022.36,0,0.0020,0,...,Узбекистан,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,Xususiy amaliyot,уста

In [6]:
len(df_no_assets)

7068

In [7]:
df_no_assets["кол-во просроч-х дней#"].isna().sum()

0

In [8]:
df_no_assets["кол-во просроч-х дней#"] = (
    df_no_assets["кол-во просроч-х дней#"]
    .astype(str)                     
    .str.replace(r"[^\d.]", "", regex=True)  
    .astype(float)                   
    .astype(int)                  
)

In [9]:
df_no_assets["кол-во просроч-х дней#"].dtype

dtype('int64')

In [10]:
df_no_assets.dropna(subset=["статус кредита"], inplace=True)

In [11]:
df_no_assets['статус кредита'].value_counts()

статус кредита
Активный     6993
Списанный      75
Name: count, dtype: int64

In [12]:
df_copy = df_no_assets.copy()
df_copy.columns

Index(['app', 'сумма выдачи', 'дата выдачи', 'дата погашения',
       'срок кредита (месяц)', 'статус кредита', 'кредитный портфель#',
       'кредитный портфель вал.#', 'портфель/итог(%)#', 'остаток стандарт#',
       'остаток стандарт вал.#', 'остаток просрочки#',
       'остаток просрочки вал.#', 'остаток пролонг#', 'остаток пролонг вал#',
       'остаток пролонг просроч.#', 'остаток пролонг просроч. вал.#',
       'остаток судопро-во#', 'остаток судопро-во вал.#',
       'лицевой счет процент', 'начисленные проценты#',
       'лицевой счет процент. внесис-й.', 'начисленные проценты внесис-й#',
       'лиц.счет текущего счета', 'остаток на тек.счете#', 'цикл',
       'кредитный продукт', 'цель кредита', 'процентная ставка',
       'дата просрочки', 'кол-во просроч-х дней#',
       'кол-во просроч-х дней по ос#', 'кол-во просроч-х дней по %#',
       'просроченная сумма по ос #', 'просроченная сумма по % #',
       'общ. кол. дни просрочки #', 'макс-я. кол. дни просрочки',
       'общ. кол. раз просрочки #', 'филиал', 'офис', 'кредитный специалист',
       'залоговая стоимость #', 'наименование залога', 'дата рождения',
       'возраст', 'пол', 'национальность', 'страна', 'область \город',
       'регион \город', 'село', 'адрес месторождения', 'семейное положение',
       'количество членов семьи', 'образование', 'место работы', 'должность'],
      dtype='object')

In [14]:
df_copy['дата выдачи'] = pd.to_datetime(df_copy['дата выдачи'], format='%d.%m.%Y')
df_copy['дата выдачи']

143     2023-08-11
212     2023-09-05
214     2023-08-18
261     2023-09-04
282     2023-09-13
           ...
12300   2025-06-02
12302   2025-06-02
12303   2025-06-02
12305   2025-06-02
12306   2025-06-02
Name: дата выдачи, Length: 7068, dtype: datetime64[ns]

In [15]:
current_date = pd.to_datetime('02.06.2025', format='%d.%m.%Y')
current_date

Timestamp('2025-06-02 00:00:00')

In [16]:
df_copy["дата выдачи"] = pd.to_datetime(df_copy["дата выдачи"], dayfirst=True)
df_copy["дата выдачи"]

143     2023-08-11
212     2023-09-05
214     2023-08-18
261     2023-09-04
282     2023-09-13
           ...
12300   2025-06-02
12302   2025-06-02
12303   2025-06-02
12305   2025-06-02
12306   2025-06-02
Name: дата выдачи, Length: 7068, dtype: datetime64[ns]

In [17]:
df_copy["months_diff"] = (current_date.year - df_copy["дата выдачи"].dt.year) * 12 + (current_date.month - df_copy["дата выдачи"].dt.month)
df_copy["months_diff"]

143      22
212      21
214      22
261      21
282      21
         ..
12300     0
12302     0
12303     0
12305     0
12306     0
Name: months_diff, Length: 7068, dtype: int32

In [18]:
df_matured = df_copy[df_copy["months_diff"] >= 6]

In [19]:
df_matured.head()

,app,сумма выдачи,дата выдачи,дата погашения,срок кредита (месяц),статус кредита,кредитный портфель#,кредитный портфель вал.#,портфель/итог(%)#,остаток стандарт#,...,область \город,регион \город,село,адрес месторождения,семейное положение,количество членов семьи,образование,место работы,должность,months_diff
143,C-00-52877,5000000.0,2023-08-11,09.08.2024,12.0,Списанный,3746309.4,0,0.0028,0,...,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amalyot,уста,22
212,C-00-53282,5000000.0,2023-09-05,05.09.2024,12.0,Списанный,4580890.3,0,0.0034,0,...,ФАРГОНА ВИЛОЯТИ,ФУРКАТ ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amaliyot,уста,21
214,C-00-53012,4000000.0,2023-08-18,16.08.2024,12.0,Списанный,478947.03,0,0.0003,0,...,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,xususiy amaliyot,богбон,22
261,C-00-53277,5000000.0,2023-09-04,04.09.2024,12.0,Списанный,319060.65,0,0.0002,0,...,ФАРГОНА ВИЛОЯТИ,КУВА ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалийёт,Шифокор,21
282,C-00-53533,4000000.0,2023-09-13,13.09.2024,12.0,Списанный,2673022.36,0,0.0020,0,...,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,Xususiy amaliyot,уста,21

In [20]:
overdue_col = "кол-во просроч-х дней#"

In [21]:
df_matured["is_bad_client"] = (
    (df_matured[overdue_col] >= 60) | 
    (df_matured["статус кредита"].str.lower() == "списанный")
)

In [22]:
df_matured["is_bad_client"].value_counts()

is_bad_client
False    3289
True      384
Name: count, dtype: int64

In [23]:
npl_ratio = df_matured["is_bad_client"].mean() * 100
print(f"NPL: {npl_ratio:.2f}%")

NPL: 10.45%

In [24]:
df_matured.head()

,app,сумма выдачи,дата выдачи,дата погашения,срок кредита (месяц),статус кредита,кредитный портфель#,кредитный портфель вал.#,портфель/итог(%)#,остаток стандарт#,...,регион \город,село,адрес месторождения,семейное положение,количество членов семьи,образование,место работы,должность,months_diff,is_bad_client
143,C-00-52877,5000000.0,2023-08-11,09.08.2024,12.0,Списанный,3746309.4,0,0.0028,0,...,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amalyot,уста,22,True
212,C-00-53282,5000000.0,2023-09-05,05.09.2024,12.0,Списанный,4580890.3,0,0.0034,0,...,ФУРКАТ ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,xususiy amaliyot,уста,21,True
214,C-00-53012,4000000.0,2023-08-18,16.08.2024,12.0,Списанный,478947.03,0,0.0003,0,...,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,xususiy amaliyot,богбон,22,True
261,C-00-53277,5000000.0,2023-09-04,04.09.2024,12.0,Списанный,319060.65,0,0.0002,0,...,КУВА ТУМАНИ,NaN,NaN,NaN,1.0,Среднее,хусусий амалийёт,Шифокор,21,True
282,C-00-53533,4000000.0,2023-09-13,13.09.2024,12.0,Списанный,2673022.36,0,0.0020,0,...,УЗБЕКИСТОН ТУМАНИ,NaN,NaN,NaN,NaN,Среднее,Xususiy amaliyot,уста,21,True

In [25]:
df_matured.columns

Index(['app', 'сумма выдачи', 'дата выдачи', 'дата погашения',
       'срок кредита (месяц)', 'статус кредита', 'кредитный портфель#',
       'кредитный портфель вал.#', 'портфель/итог(%)#', 'остаток стандарт#',
       'остаток стандарт вал.#', 'остаток просрочки#',
       'остаток просрочки вал.#', 'остаток пролонг#', 'остаток пролонг вал#',
       'остаток пролонг просроч.#', 'остаток пролонг просроч. вал.#',
       'остаток судопро-во#', 'остаток судопро-во вал.#',
       'лицевой счет процент', 'начисленные проценты#',
       'лицевой счет процент. внесис-й.', 'начисленные проценты внесис-й#',
       'лиц.счет текущего счета', 'остаток на тек.счете#', 'цикл',
       'кредитный продукт', 'цель кредита', 'процентная ставка',
       'дата просрочки', 'кол-во просроч-х дней#',
       'кол-во просроч-х дней по ос#', 'кол-во просроч-х дней по %#',
       'просроченная сумма по ос #', 'просроченная сумма по % #',
       'общ. кол. дни просрочки #', 'макс-я. кол. дни просрочки',
       'общ. кол. раз просрочки #', 'филиал', 'офис', 'кредитный специалист',
       'залоговая стоимость #', 'наименование залога', 'дата рождения',
       'возраст', 'пол', 'национальность', 'страна', 'область \город',
       'регион \город', 'село', 'адрес месторождения', 'семейное положение',
       'количество членов семьи', 'образование', 'место работы', 'должность',
       'months_diff', 'is_bad_client'],
      dtype='object')

In [26]:
selected_features = [
    'дата выдачи', 'семейное положение',
    'сумма выдачи', 'кредитный портфель#' ,'срок кредита (месяц)', 'цикл', 'цель кредита', 'процентная ставка', 
    'возраст', 'пол', 'область \город', 'регион \город','количество членов семьи',
    'образование', 'должность', 'is_bad_client'
]

In [27]:
selected = df_matured[selected_features]
selected.head()

,дата выдачи,семейное положение,сумма выдачи,кредитный портфель#,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,область \город,регион \город,количество членов семьи,образование,должность,is_bad_client
143,2023-08-11,NaN,5000000.0,3746309.4,12.0,1.0,Миграция,72.0,47.0,М,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,Среднее,уста,True
212,2023-09-05,NaN,5000000.0,4580890.3,12.0,1.0,Миграция,72.0,28.0,М,ФАРГОНА ВИЛОЯТИ,ФУРКАТ ТУМАНИ,NaN,Среднее,уста,True
214,2023-08-18,NaN,4000000.0,478947.03,12.0,1.0,Миграция,72.0,30.0,Ж,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,1.0,Среднее,богбон,True
261,2023-09-04,NaN,5000000.0,319060.65,12.0,1.0,Миграция,72.0,40.0,М,ФАРГОНА ВИЛОЯТИ,КУВА ТУМАНИ,1.0,Среднее,Шифокор,True
282,2023-09-13,NaN,4000000.0,2673022.36,12.0,1.0,Миграция,72.0,22.0,М,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,Среднее,уста,True

In [28]:
selected.rename(columns={'кредитный портфель#': 'остаток суммы'}, inplace=True)
selected.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,область \город,регион \город,количество членов семьи,образование,должность,is_bad_client
143,2023-08-11,NaN,5000000.0,3746309.4,12.0,1.0,Миграция,72.0,47.0,М,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,Среднее,уста,True
212,2023-09-05,NaN,5000000.0,4580890.3,12.0,1.0,Миграция,72.0,28.0,М,ФАРГОНА ВИЛОЯТИ,ФУРКАТ ТУМАНИ,NaN,Среднее,уста,True
214,2023-08-18,NaN,4000000.0,478947.03,12.0,1.0,Миграция,72.0,30.0,Ж,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,1.0,Среднее,богбон,True
261,2023-09-04,NaN,5000000.0,319060.65,12.0,1.0,Миграция,72.0,40.0,М,ФАРГОНА ВИЛОЯТИ,КУВА ТУМАНИ,1.0,Среднее,Шифокор,True
282,2023-09-13,NaN,4000000.0,2673022.36,12.0,1.0,Миграция,72.0,22.0,М,ФАРГОНА ВИЛОЯТИ,УЗБЕКИСТОН ТУМАНИ,NaN,Среднее,уста,True

In [29]:
selected.isna().sum()

дата выдачи                   0
семейное положение         1132
сумма выдачи                  0
остаток суммы                 0
срок кредита (месяц)          0
цикл                          0
цель кредита                  0
процентная ставка             0
возраст                       0
пол                           0
область \город                0
регион \город                 0
количество членов семьи      56
образование                 321
должность                   488
is_bad_client                 0
dtype: int64

In [30]:
selected['дата выдачи'] = pd.to_datetime(selected['дата выдачи'], dayfirst=True, errors='coerce')

In [31]:
selected['year'] = selected['дата выдачи'].dt.year

In [32]:
obj_df=selected.select_dtypes(include=['object']).copy()

In [33]:
def find_unique(col):
    print(col,":",obj_df[col].unique())

In [34]:
for col in obj_df.columns:
  find_unique(col)

семейное положение : [nan 'Женат \\ замужем' 'Холост \\ незамужем' 'Рахимов Юсуфжон'
 'В разводе' 'Вдовец \\ вдова' 'Mirzayeva Gulshanoy']
остаток суммы : [3746309.4 4580890.3 478947.03 ... 7799197.59 4082987.9 7810148.67]
цель кредита : ['Миграция' 'Деҳқончилик, томорқа хўжалигини ривожлантириш'
 'Таъмирлаш ишлари учун  (оилавий тадбирлар, таълим, даволаниш)'
 'Оилавий ва шахсий эҳтиёжлар (оилавий тадбирлар, таълим, даволаниш)'
 'Чорвачиликни ривожлантириш'
 'Ҳунармандчилик, касаначиликни ривожлантириш'
 'Энергия тежовчи ускуналар сотиб олиш, ўрнатиш'
 'Ички туризмни ривожлантириш' 'Савдо' 'Хизмат курсатиш' 'Ишлаб чикариш']
пол : ['М' 'Ж']
область \город : ['ФАРГОНА ВИЛОЯТИ' 'НАМАНГАН ВИЛОЯТИ' 'АНДИЖОН ВИЛОЯТИ' 'ТОШКЕНТ ШАХРИ'
 'ТОШКЕНТ ВИЛОЯТИ']
регион \город : ['УЗБЕКИСТОН ТУМАНИ' 'ФУРКАТ ТУМАНИ' 'КУВА ТУМАНИ' 'ЧУСТ ТУМАНИ'
 'КУКОН ШАХРИ' 'ДАНГАРА ТУМАНИ' 'УЧКУПРИК ТУМАНИ' 'ТУРАКУРГОН ТУМАНИ'
 'ОЛТИАРИК ТУМАНИ' 'ПОП ТУМАНИ' 'УЧКУРГОН ТУМАНИ' 'ЯНГИКУРГОН ТУМАНИ'
 'БУВАЙДА ТУМАНИ' 'МИНГБУЛОК ТУМАНИ' 'НАМАНГАН ШАХРИ' 'ФАРГОНА ТУМАНИ'
 'ФАРГОНА ШАХРИ' 'БОГДОД ТУМАНИ' 'КОСОНСОЙ ТУМАНИ' 'НАМАНГАН ТУМАНИ'
 'ИЗБОСКАН ТУМАНИ' 'АНДИЖОН ТУМАНИ' 'БЕШАРИК ТУМАНИ' 'ТОШЛОК ТУМАНИ'
 'БАЛИКЧИ ТУМАНИ' 'АНДИЖОН ШАХРИ' 'ПАХТАОБОД ТУМАНИ' 'ОЛТИНКУЛ ТУМАНИ'
 'НОРИН ТУМАНИ' 'ШАХРИХОН ТУМАНИ' 'МАРГИЛОН ШАХРИ' 'СУХ ТУМАНИ'
 'ЧОРТОК ТУМАНИ' 'КУВАСОЙ ШАХРИ' 'КУРГОНТЕПА ТУМАНИ' 'ЖАЛОЛКУДУК ТУМАНИ'
 'ШАЙХОНТОХУР ТУМАНИ' 'БУКА ТУМАНИ' 'АСАКА ТУМАНИ' 'РИШТОН ТУМАНИ'
 'УЙЧИ ТУМАНИ' 'ХУЖАОБОД ТУМАНИ' 'СИРГАЛИ ТУМАНИ']
образование : ['Среднее' 'Средне-специальное' 'Высшее' nan 'Неоконченное высшее'
 'Урта махсус' 'Среднее_x000D_\n' 'урта-махсус' 'Начальное']
должность : ['уста' 'богбон' 'Шифокор' 'шофёр' 'Касаначи' 'Ишчи' 'ёрдамчи' 'нафакахур'
 'темирчи' 'Тикувчи' 'дурадгор' 'дехкон' 'Нонвой' 'кабобпаз'
 'Сантехник уста' nan 'tikuvchi' 'usta' 'quruvchi usta' 'тикувчи'
 'Хайдовчи ' 'хайдовчи' 'автомабил устаси' 'qassob' 'xaydovchi' 'Оператор'
 'Tikuvchi' 'tikuvchi/chorvador' 'дех?он' 'sotuvchi' 'уй' 'пайвандчи'
 'Хайкалтарош уста ' 'савдогар' 'Хайдовчи' 'Тикувчи ' 'tikish-bichish '
 'Чорва мол парвариши,утлатиш' 'Шафер ' 'савдода ёрдамчи' 'Дастурчи'
 'milliy non va patirlarni tayorlash ' 'сотувчи' 'нафакада' 'Sotuvchi'
 'Уста-сантехник' 'Савдода ёрдамчи ва нафакахур' 'ishchi'
 'savdoda yordamchi' 'chorvador' 'сартарош' 'нафакада ' 'савдога ёрдамчи'
 'ишчи' 'Sartarosh' 'bog‘bon' 'Тадбиркор' 'Taksist' 'уй хужалиги' 'oshpaz'
 'usta (avto sevis kraska ) ' 'автомобил устаси' 'Orif Ota Choyxonasi'
 'Курувчи уста ' 'sotuvchi ' '?урувчи уста' 'MTM mudirasi' 'чевар'
 'yordamchi ishchi' 'Boshqaruvchi' 'сотувчи(Музкаймок)' 'Уста' 'Пенсионер'
 'mchj bino egasi ' 'savdogar' 'Nafaqaxo‘r' 'uyda' 'чорвадор'
 'Oddiy ishchi' 'Savdogar' 'ошпаз' 'dexqon' 'Чорвачилик' 'nafaqahor '
 'Чорвадор' 'chevar ' 'автомобиль устаси' 'Bog‘bon' 'avtomoobil usta'
 'haydovchi' 'Afitsanka' 'уй бекаси' 'Болаларга караш' 'IShchi'
 'Уй бекаси' 'корпус ишчиси' 'Dexqon' 'тикувчилик' 'tadbirkor'
 'курувчи уста' 'Raxbar' 'ошхона ишчиси' 'Qandolatchi' 'хамшира' 'nonvoy'
 'тарбиячи' 'Usta' 'savdo' 'тадбиркор' 'ishchi ' 'Нафакада'
 'Ip yigiruvchi' 'дуппидуз' 'nazoratchi' 'Tadbirkor' 'Дурадгор' 'chevar'
 'Пасуда мойшик' 'тарбиячи ' 'tikuvchi ' 'ish boshqaruvchi '
 'Video Montaj' 'ish yurituvchi ' 'Cантехник уста ' 'Савдогар'
 'ишлаб чикариш цехда ишчи' 'Уй хамшираси' 'декаратив гулларни етиштириш'
 'Хусусий Мини футда фаррош' 'фаррош' 'Автомобил устаси' 'marketolog'
 'Nafaqada' 'Уктувчи' 'Kasir' 'Репетиторлик' 'курувчи уста '
 'йигирув сехи ишчиси' 'Нафа?ада' 'Укитувчи' 'Дех?он' 'автомашина устаси'
 'хайдовчи таксист' 'nafaqaxo‘r' 'пиширикчи' 'Буфетчи' 'mudira ' 'Уйда'
 'совдогар' 'Afitsantka' 'Иш юритувчи'
 'tadbirkor chorva mollari oldi sottisi bilan ' 'Пайвандчи Уста'
 'репетитор' 'ish boshqaruvchi' 'Хамшира' 'уста хунарманд' 'тадбиркор '
 'уй ишлари' 'Chevar' 'Хайдовчи (Юк ташувчи)' 'sport yo‘riqchisi '
 'нафакахур савдода ёрдамчи' 'нафа?ада' 'O‘qtuvchi' 'Нафака' 'Дехкон'
 'pishiriqchi ' 'Ish boshqaruvchi '
 'Хусусий пайпок ишлаб чикариш корхонасида тикувчи' 'нонвой'
 'Moshina ustasi' 'Ошпаз' 'Xaydovchi' 'Сотувчи' 'Савдода ёрдамчи'
 'Dexqon ' 'Заводда ишчи' 'Савдога ёрдамчи' 'бичувчи ва тикувчи' 'usta '
 'тушум йигувчи' 'хизмат курсатувчи' 'kadir ' 'Qurilish Ustasi'
 'кандолатчи' 'писта бодом сотувчи'
 'Сантехника ишлари Электромонтаж ишлари' 'Quruvchi usta' 'Ходима'
 'nafaqada' 'Ёлланма ишчи' 'Baliqchilik' 'хусусий бугалтер'
 'курувчи уста 0 дан' 'Ошпаз, Куръер' 'nafakaho‘r' 'уста курувчи'
 'механик' 'Афтотех хизмат ишчиси' 'o‘qituvchi' 'nafaqada  tikuvchi'
 'Nafaqaxor' 'мошина устаси' 'Темирчи-Уста' 'фармасефт '
 ' савдога ёрдамчи' 'Баликчилик билан шугулланади' 'ishboshqaruvchi'
 'Ishchi' 'raxbar' 'Konsultant' 'quilish ustasi' 'farrosh' 'Nonvoy'
 'shoberdi qishlog‘ida' 'бролер етиштириш сехи ишчиси ' 'чевар '
 'dexqon bozori' 'xususiy amaliyot' 'Кассоб' 'Oshpaz' 'Уста-сирчи' 'USta'
 'hamshira' 'нафака' 'Фаррош' 'chorvachilik' 'Цехда иш юритувчи'
 'Svarshik' 'иссикхоналарда махсулот етиштириш (уй шароитида)'
 'Temirchilik' 'куткарувчи' 'компютер устаси' 'metal ta`mirlash '
 'сантехник уста' 'дехкончилик' 'кандолат махсулотлари пишириб сотиш'
 'Salonchi' 'ёрдамчи тарбиячи' 'Kartoshka sotadi' 'хужалик мудири'
 'автомашиналар сотувчиси' 'МДФ Ешик-ром уста' 'Ходим' 'сех ишчиси'
 'авто мойка ювувчи' 'нонвойчилик' 'Бош ошпаз' 'Chevarchilik'
 'Pishiriq savdogari' 'болалар кийим кечаги савдоси' 'hofiz' 'Non voy'
 'кандолат устаси' 'Zalga qarovchi' 'Qurilish ustasi' 'Usta (quruvchi)'
 'Сотувчи ' 'Telefon ustasi' 'уй бекаси ' 'Matematikadan o‘qituvchi'
 'чигитни кайта ишлаш сехи ишчиси' 'dexqonchilik' 'укитувчи'
 'комютер устаси' 'пазанда' 'Тарбиячи ' 'фасфут бургер тайёрловчи '
 'Usta (oddelka)' 'Savdogar (detskiy kiyim)' 'Инспектор'
 'traktor xaydovchisi' 'кондитер-ёрдамчи' 'шафёр ' 'Onlayn taksi'
 'назоратчи' 'buyurtma asosida tovarlarni yetkazib berish'
 'сомса пишириш билан шугулланади' 'савдогар ' 'хайдовчи , уста'
 'преслаш сехи ишчиси ' 'шафер' 'нафакада ва тикувчи' 'Tozalovchi'
 'дси ходими' 'Тикувчи-дизайнер' 'Дехгон' 'богбончилик ' 'Кандолатчи'
 'Ў?итувчи' 'дех?он / сотувчи' 'савдода ёрдвмчи' 'Назоратчи Сокчи '
 'Mebel ustasi' 'svarshik' 'аёллар кийим кечаги' 'тикувчи чевар '
 'чевар тикувчи ' 'машина устаси' 'ёгоч устаси ' 'гузаллик салони'
 'пишири?чи' 'Савдогар ёрдамчиси' 'курилиш устаси' 'Тадбиркор-Ошпаз '
 'Курувчи-уста' 'bog‘bon ' 'Issiqxona' 'Тарбиячи' 'компютер хизмати '
 'косиб' 'нафакада(тикувчи)' 'Репетитор хизмати' 'сварчик' 'Кутубхоначи'
 'dispetcher' 'nafaqaxor' 'Юк мошна минади' 'Chorvachilik' 'тикувчи ишчи'
 'озик овкат магазин' 'дех?он/сотувчи' 'Бозорчи ' 'Болаларга ?араб туриш'
 'Рахбари ' 'Tarbiyachi' 'Косиб' 'ishchi va sotuvchi' 'чилангар '
 'omborda mutaxasis ' 'mebel uyda' 'сотувчи/тикувчи' 'Mudira'
 'нафакада (сотувчи)' 'кондитер ' 'Курувчи уста' 'stanokchi ' 'Malyar'
 'пенсионер' 'artist' 'Chakana savdogar' 'гузаллик салони ишчиси'
 'Sotuvchi ' 'укитувчи ' 'ТИкувчи' 'уйда ' 'Булим рахбари' 'нафaкада'
 'Рахбар' 'Afitsant' 'Фаробий савдо комплексида савдогар'
 'Savdogar (Chakana savdo)' 'Nazoratchi' 'Tikuvchi ' 'To‘quvchi' 'taksi'
 'Носир ошхонасида ошхона ишчиси ' 'Авто электирик' 'винтелация устаси '
 'услубчи ' 'Davlat ijrochisi' 'сирчи уста' 'хоким ёрдамчиси' 'Tayyorlov '
 'новвой' 'ёлланма ишчи' 'Дуродгор' 'электр устаси' 'Xamir tayyorlaydi'
 'уста , хайдовчи' 'elektrik' 'АТГ ходими' 'Shafyor'
 'Usta (Issiqxonasi mavjud)' 'Ish boshqaruvchi' 'мебел тамирловчи уста'
 'сут катик сотишади' 'уста ' 'хусусий амалиёт' 'pishiriqchi'
 'ish yurutuvchi' 'ustachilik' 'Chevar tikuvchi' 'tarbiyachi'
 'Buyurtmachi' 'taksis ' 'qoravul' 'Повор ошпаз' 'xaydovchi ' 'Сирчи уста'
 'tarozichi' 'Payvandchi' 'ходим' 'аёллар оёк кийимлари сотади'
 'Уста (эшик-ром)' 'мехмонхона бошкарувчиси' 'чорвачи ' 'otdelkachi '
 'тозаловчи' 'савдогарр' 'Tikuvchilik' 'кадрлар бўлими мутахасиси' 'kosib'
 'тикувчи (хунарманд)' ' сотувчи' 'туман худудида' 'Нафакада(сотувчи)'
 'Репетитор' 'Mavsumiy ishchi' 'operator' 'tikuvchilik' 'haydovchi '
 'Савдогар ' 'Nafaqa' 'Нафакахур' 'Kassir' 'isuzi boshqaruvchisi'
 'Уста-курувчи' 'МФЙ Раиси' 'Buxgalter' 'nonvoy '
 'Damas xaydaydi (taksist)' 'уйда' 'савдода ёдамчи' 'sotuvchi Savdogar'
 'boyoq xodimi ' 'Savdogar (Moshina)' 'Тадбиркор куёш батареякаси'
 'Кореяда заводда ишлайди' 'Fermer' 'tarbiyachi ' 'O‘qituvchi'
 'Дорихона сотувчи' 'Chorvachilik bilan' 'Хайдовчи(Таксист)' 'Богбон'
 'Укитувчи ' 'pilaramada ishchi' 'Xotin qizlar Faoli' 'Mexanik'
 'рус тили укитувчиси' 'Pishiriqchi' 'хайдовчи таксист ' 'Duradgor usta'
 'Mebel (stol stul)' 'ДУКОН ОЧАДИ' 'Oshpaz (Shashlukpaz)' 'TADBIRKOR'
 'дехкон бозорида к/х махсулотлари сотиш' 'xizmat ko‘rsatish (pilorama)'
 'ёрдамчи савдода' 'o‘qituvchi ' 'nafaqada / тикувчи' 'Uqituvchi'
 'Oylaviy ishlab chiqarish' 'satuvchi' 'мебел ясовчм уста'
 'Хайдовчи таксист ' 'уйда чеварчилик килиш учун' 'Имрон ошхонада эгаси'
 'ОЛИБ СОТАДИ' 'Ish yurituvchi' 'супурги етиштиради' 'Пиширикчи'
 'Xo‘jalik ishlar mudiri' 'салтарош' 'мавсумий мева сотади'
 'Direktor O‘rinbosari' 'nafaqada / sotuvchi' 'savdoda ytordamchi'
 'Учкуприк тумани' 'мева сотади' 'репитотор' 'электрик' 'Elektrik'
 'usta quruvchi' 'Yoshlar yetakchisi' 'Undiruv mutaxassisi' 'фермер'
 'авто устаси' 'иш ютирувчи' 'Moyshik' 'кичик тиббий ходим' 'Kontrolchi'
 'тракторчи' 'Pensioner' 'Кондитер ёрдамчиси' 'ИШЧИ'
 'сотувчи мавсумий мевалар сотади ' 'Somsapaz' 'tikish-bichish'
 'Савдага Ёрдамчи' 'CHevar' 'Mini Osh Xona'
 'Uyda chorvachilik bilan shug‘ullanadi'
 'Xonadonida chorvachilik bilan shug‘ullanadi' 'Компьютер устаси'
 'телефон устаси' 'Dexqonchilik' 'quruvchi' 'шеф повур' 'CHORVADOR'
 'Otdelkachi' 'Oshxona' 'Taksis' 'nafaqada / tikuvchi' 'сантехник'
 'Manikyurchi' 'nafaqada / dexqon' 'Нафакхур' 'беморларга караш'
 'иш бошкарувчи ' 'UNICON-SOFT да туман рахбари' 'Бармен' 'avtomabil usta'
 'Chorvador' 'somsapaz' 'shifokor' 'пенсионер ва савдогар' 'коровул'
 'santexnik' 'Fotostudiya' 'Пайвандчи' 'дехкон молбокар' 'Savdoqar'
 'Механик' 'kuruvchi usta ' 'Avtomobil Ustasi' 'сех ишчиси '
 'Ingliz tilidan dars beradi' 'уйда курпа тушак килади' 'товар олди сотти'
 'Shashlikpaz' 'baxor bolajon bog‘chada buxgalter' 'kafel ustasi'
 'Автомобил устаси ' 'Avtomobil ustasi' 'Osgpaz' 'йигирув сехи ишчиси '
 'курувчи уста  ва таксист ' 'чилангар' 'савдогар трикотож' 'Нафакахур '
 'уста ва таксист ' 'Novvoy' 'Nonvoy Va Haydovchi'
 'хизмат курсатиш шашликпаз' 'Назоратчи ' 'Сартарош ' 'Директор'
 'касаначи' 'Нафакада (дехкон)' 'савдогар ёйма '
 'салон аёлларга хизмат курсатиш' 'Taksi' 'Юкори синф математика укитувчи'
 'курувчи' 'Qoravul' 'савдо дукон' 'хунарманд' 'Xaydov Traktor xaydaydi'
 'ППХБ' 'Xususiy emakxona' 'жахон бозорда савдо'
 'Jismoniy shahslarga murakkab bo‘lmagan qurilish-tamirlash ishlar'
 'укитувчм' 'доришунос' 'маляр устаси ' 'Oshxona ishchisi'
 'дехкон хужалиги' 'богдорчилик фермасида ишчи' 'Aptekada Sotuvchi'
 'потуг поликлиникада коровул ва махаллани повури' 'Хунарманд' '?оровул'
 'ёг догловчи ' 'уктувчи ' 'дехкончилик учун' 'уста (маиший техник)'
 'Kompyuter ustasi' 'Баликчи' 'пайвандчи уста' 'uy bekasi '
 'Ayollar ro‘moli sotuvchisi' 'Chevar ' 'Тасвирчи' 'Haydovchi'
 'Traktor Xaydovchisi' 'богчада тарбиячи' 'Асалчи ' 'Назоратчи'
 'Dispecher' 'Олий тоифали хамшира' 'Sex raxbari' 'тикувчилик '
 'ипотека банкда коровул' 'Gandbol murabbiyi' 'Сомса пиширади' 'Баликчи '
 'Нафвкада' 'Дехкон бозолрлрда к/х меваларини сотиш' 'уста автомобил'
 'Дупидуз' 'Сартарош' 'Navbatchi' 'Akfa o‘rnatuvchi'
 'савдогар(онлайн дукон)' 'Курувчи Уста' 'Савдогар(Гушт махсулотлари)'
 'савдода' 'Иш бошкорувчи' 'МТМ' 'savdodas yordamchi' 'уй хамшираси'
 'savododa yordamchi' 'тукувчи' 'дизайнер' 'вейзажист(ишчи)' 'Стоматолог'
 'механизатор' 'оддий ишчи ' 'кондитор махсулоти ишлаб чикаради'
 'Ichchi xodim' 'уста сантехник' 'тикувчи хунарманд'
 'чорва молларини етиштириш' 'Qutqaruvchi' 'Чодак Икватрял МЧЖ' 'Коровул'
 'Богчада тарбиячи' 'Савдогар сочик дастурхон' 'шифокор' 'Машина уста '
 'моляр устаси ' 'Болаларга караб туриш' 'chorvador ' '?урквчи уста'
 'musiqa murabbiy' 'Биринчи уринбосар йордамчиси'
 'Дехкон бозорида к/х махсулотларини сотиш' 'Rahbar'
 'Yog‘och memorchiligi' 'авто уста' 'Konditer' 'мутахасис' 'Техник'
 'tadbirkor oshpaz' 'У?итувчи' 'Дехкончилик' 'хайдовчи тасист ' 'Коравул'
 'Suvchi' 'Мебель устаси' 'hunarmandchilik' 'Рахбар уринбосари'
 'taxlovchi' 'doimiy ishchi' 'чарвадор' 'стилист' 'Chorva'
 'oshpaz somsapaz' 'ёш болалар масажчиси ' 'Чорвадор ' 'Нафакада '
 'шифохона' 'Oddiy Ishchi' 'акфа ишлаб чикаради' 'савдога ёрджамчи'
 'темирчи уста' 'чигит сехи ишчиси ' 'Sanatkor' 'Хусусий тарбиячи'
 'катта оператор' 'administrator ' '1' 'Xarbiy' 'Usta Bo‘yoqchi' 'Чевар'
 'Фермер' 'Savdo' 'хисобчи' 'туникасоз' 'ishchi xodim' 'садода ёрдамчи'
 'кандолат махсулотлари' 'svarka ustasi' 'сотувчи ' 'adelka' 'mutaxasis'
 'Атлас ва адрас тукиш' 'савдодла ёрдамчи' 'CHevar ' 'Акфа уста'
 'репититорлик хизмати' 'Operator' 'Эликтерик' 'кутубхон' 'Dehqonchilik'
 'тикуви' 'Иссикхона махсулотларини етиштириш' 'payvantchi usta'
 'Svarshik usta' 'Musiqachi ' 'Mehmonhonada adminstrator '
 'Ёшлар ишлар агентлиги етакчи' 'Idish Yuvuvchi' 'экскаватор хайдовчиси'
 'Xizmat korsatish' 'Savdogar ' 'бокувчи (чорва)' 'тикувчи  '
 'тикуш бичиш' 'Fermer xo‘jaligi' 'usta-quruvchi' 'Xamshira'
 'дехкон супурги етиштиради' 'Нонвойчилик' 'Устачилик' 'Электрик'
 'Ishchi xodim' 'уста ва нонвой' 'Chorva Boqadi' 'Hazinabon' 'Чеварчилик'
 'маиший техникаларни жихозловчи' 'Елхон МФЙ' 'Nonvoychilik' 'Уй бекаси '
 'yollanma ishchi ' 'Ёрдамчи ишчи' 'Дарвоза уста' 'Parranda boqadi'
 'Мошина олиб сотар' 'Хусусий Оператор' 'Santexnik usta' 'устачилик'
 'Chorvachilik ' 'Meva Oldi Sotdisi Bilan Shug‘illanadi ' 'dehqon']

In [35]:
selected.columns

Index(['дата выдачи', 'семейное положение', 'сумма выдачи', 'остаток суммы',
       'срок кредита (месяц)', 'цикл', 'цель кредита', 'процентная ставка',
       'возраст', 'пол', 'область \город', 'регион \город',
       'количество членов семьи', 'образование', 'должность', 'is_bad_client',
       'year'],
      dtype='object')

In [36]:
cols_to_clean = [
    'цель кредита',
    'пол', 'образование', 'должность', 'область \город',
       'регион \город' 
]

In [37]:
for col in cols_to_clean:
    selected[col] = selected[col].astype(str).str.strip().str.lower()

In [38]:
bad_values = {
    'образование': [
        'o‘qituvchi 25-maktab',
        'xususiy amaliyot'
    ]
}

In [39]:
for col, values in bad_values.items():
    selected = selected[~selected[col].astype(str).str.strip().str.lower().isin([v.lower() for v in values])]

selected = selected.reset_index(drop=True)

In [40]:
obj_df=selected.select_dtypes(include=['object']).copy()

In [41]:
for col in obj_df.columns:
    find_unique(col)

семейное положение : [nan 'Женат \\ замужем' 'Холост \\ незамужем' 'Рахимов Юсуфжон'
 'В разводе' 'Вдовец \\ вдова' 'Mirzayeva Gulshanoy']
остаток суммы : [3746309.4 4580890.3 478947.03 ... 7799197.59 4082987.9 7810148.67]
цель кредита : ['миграция' 'деҳқончилик, томорқа хўжалигини ривожлантириш'
 'таъмирлаш ишлари учун  (оилавий тадбирлар, таълим, даволаниш)'
 'оилавий ва шахсий эҳтиёжлар (оилавий тадбирлар, таълим, даволаниш)'
 'чорвачиликни ривожлантириш'
 'ҳунармандчилик, касаначиликни ривожлантириш'
 'энергия тежовчи ускуналар сотиб олиш, ўрнатиш'
 'ички туризмни ривожлантириш' 'савдо' 'хизмат курсатиш' 'ишлаб чикариш']
пол : ['м' 'ж']
область \город : ['фаргона вилояти' 'наманган вилояти' 'андижон вилояти' 'тошкент шахри'
 'тошкент вилояти']
регион \город : ['узбекистон тумани' 'фуркат тумани' 'кува тумани' 'чуст тумани'
 'кукон шахри' 'дангара тумани' 'учкуприк тумани' 'туракургон тумани'
 'олтиарик тумани' 'поп тумани' 'учкургон тумани' 'янгикургон тумани'
 'бувайда тумани' 'мингбулок тумани' 'наманган шахри' 'фаргона тумани'
 'фаргона шахри' 'богдод тумани' 'косонсой тумани' 'наманган тумани'
 'избоскан тумани' 'андижон тумани' 'бешарик тумани' 'тошлок тумани'
 'баликчи тумани' 'андижон шахри' 'пахтаобод тумани' 'олтинкул тумани'
 'норин тумани' 'шахрихон тумани' 'маргилон шахри' 'сух тумани'
 'чорток тумани' 'кувасой шахри' 'кургонтепа тумани' 'жалолкудук тумани'
 'шайхонтохур тумани' 'бука тумани' 'асака тумани' 'риштон тумани'
 'уйчи тумани' 'хужаобод тумани' 'сиргали тумани']
образование : ['среднее' 'средне-специальное' 'высшее' 'nan' 'неоконченное высшее'
 'урта махсус' 'среднее_x000d_' 'урта-махсус' 'начальное']
должность : ['уста' 'богбон' 'шифокор' 'шофёр' 'касаначи' 'ишчи' 'ёрдамчи' 'нафакахур'
 'темирчи' 'тикувчи' 'дурадгор' 'дехкон' 'нонвой' 'кабобпаз'
 'сантехник уста' 'nan' 'tikuvchi' 'usta' 'quruvchi usta' 'хайдовчи'
 'автомабил устаси' 'qassob' 'xaydovchi' 'оператор' 'tikuvchi/chorvador'
 'дех?он' 'sotuvchi' 'уй' 'пайвандчи' 'хайкалтарош уста' 'савдогар'
 'tikish-bichish' 'чорва мол парвариши,утлатиш' 'шафер' 'савдода ёрдамчи'
 'дастурчи' 'milliy non va patirlarni tayorlash' 'сотувчи' 'нафакада'
 'уста-сантехник' 'савдода ёрдамчи ва нафакахур' 'ishchi'
 'savdoda yordamchi' 'chorvador' 'сартарош' 'савдога ёрдамчи' 'sartarosh'
 'bog‘bon' 'тадбиркор' 'taksist' 'уй хужалиги' 'oshpaz'
 'usta (avto sevis kraska )' 'автомобил устаси' 'orif ota choyxonasi'
 'курувчи уста' '?урувчи уста' 'mtm mudirasi' 'чевар' 'yordamchi ishchi'
 'boshqaruvchi' 'сотувчи(музкаймок)' 'пенсионер' 'mchj bino egasi'
 'savdogar' 'nafaqaxo‘r' 'uyda' 'чорвадор' 'oddiy ishchi' 'ошпаз' 'dexqon'
 'чорвачилик' 'nafaqahor' 'chevar' 'автомобиль устаси' 'avtomoobil usta'
 'haydovchi' 'afitsanka' 'уй бекаси' 'болаларга караш' 'корпус ишчиси'
 'тикувчилик' 'tadbirkor' 'raxbar' 'ошхона ишчиси' 'qandolatchi' 'хамшира'
 'nonvoy' 'тарбиячи' 'savdo' 'ip yigiruvchi' 'дуппидуз' 'nazoratchi'
 'пасуда мойшик' 'ish boshqaruvchi' 'video montaj' 'ish yurituvchi'
 'cантехник уста' 'ишлаб чикариш цехда ишчи' 'уй хамшираси'
 'декаратив гулларни етиштириш' 'хусусий мини футда фаррош' 'фаррош'
 'marketolog' 'nafaqada' 'уктувчи' 'kasir' 'репетиторлик'
 'йигирув сехи ишчиси' 'нафа?ада' 'укитувчи' 'автомашина устаси'
 'хайдовчи таксист' 'пиширикчи' 'буфетчи' 'mudira' 'уйда' 'совдогар'
 'afitsantka' 'иш юритувчи' 'tadbirkor chorva mollari oldi sottisi bilan'
 'пайвандчи уста' 'репетитор' 'уста хунарманд' 'уй ишлари'
 'хайдовчи (юк ташувчи)' 'sport yo‘riqchisi' 'нафакахур савдода ёрдамчи'
 'o‘qtuvchi' 'нафака' 'pishiriqchi'
 'хусусий пайпок ишлаб чикариш корхонасида тикувчи' 'moshina ustasi'
 'заводда ишчи' 'бичувчи ва тикувчи' 'тушум йигувчи' 'хизмат курсатувчи'
 'kadir' 'qurilish ustasi' 'кандолатчи' 'писта бодом сотувчи'
 'сантехника ишлари электромонтаж ишлари' 'ходима' 'ёлланма ишчи'
 'baliqchilik' 'хусусий бугалтер' 'курувчи уста 0 дан' 'ошпаз, куръер'
 'nafakaho‘r' 'уста курувчи' 'механик' 'афтотех хизмат ишчиси'
 'o‘qituvchi' 'nafaqada  tikuvchi' 'nafaqaxor' 'мошина устаси'
 'темирчи-уста' 'фармасефт' 'баликчилик билан шугулланади'
 'ishboshqaruvchi' 'konsultant' 'quilish ustasi' 'farrosh'
 'shoberdi qishlog‘ida' 'бролер етиштириш сехи ишчиси' 'dexqon bozori'
 'xususiy amaliyot' 'кассоб' 'уста-сирчи' 'hamshira' 'chorvachilik'
 'цехда иш юритувчи' 'svarshik'
 'иссикхоналарда махсулот етиштириш (уй шароитида)' 'temirchilik'
 'куткарувчи' 'компютер устаси' 'metal ta`mirlash' 'дехкончилик'
 'кандолат махсулотлари пишириб сотиш' 'salonchi' 'ёрдамчи тарбиячи'
 'kartoshka sotadi' 'хужалик мудири' 'автомашиналар сотувчиси'
 'мдф ешик-ром уста' 'ходим' 'сех ишчиси' 'авто мойка ювувчи'
 'нонвойчилик' 'бош ошпаз' 'chevarchilik' 'pishiriq savdogari'
 'болалар кийим кечаги савдоси' 'hofiz' 'non voy' 'кандолат устаси'
 'zalga qarovchi' 'usta (quruvchi)' 'telefon ustasi'
 'matematikadan o‘qituvchi' 'чигитни кайта ишлаш сехи ишчиси'
 'dexqonchilik' 'комютер устаси' 'пазанда' 'фасфут бургер тайёрловчи'
 'usta (oddelka)' 'savdogar (detskiy kiyim)' 'инспектор'
 'traktor xaydovchisi' 'кондитер-ёрдамчи' 'шафёр' 'onlayn taksi'
 'назоратчи' 'buyurtma asosida tovarlarni yetkazib berish'
 'сомса пишириш билан шугулланади' 'хайдовчи , уста' 'преслаш сехи ишчиси'
 'нафакада ва тикувчи' 'tozalovchi' 'дси ходими' 'тикувчи-дизайнер'
 'дехгон' 'богбончилик' 'ў?итувчи' 'дех?он / сотувчи' 'савдода ёрдвмчи'
 'назоратчи сокчи' 'mebel ustasi' 'аёллар кийим кечаги' 'тикувчи чевар'
 'чевар тикувчи' 'машина устаси' 'ёгоч устаси' 'гузаллик салони'
 'пишири?чи' 'савдогар ёрдамчиси' 'курилиш устаси' 'тадбиркор-ошпаз'
 'курувчи-уста' 'issiqxona' 'компютер хизмати' 'косиб' 'нафакада(тикувчи)'
 'репетитор хизмати' 'сварчик' 'кутубхоначи' 'dispetcher'
 'юк мошна минади' 'тикувчи ишчи' 'озик овкат магазин' 'дех?он/сотувчи'
 'бозорчи' 'болаларга ?араб туриш' 'рахбари' 'tarbiyachi'
 'ishchi va sotuvchi' 'чилангар' 'omborda mutaxasis' 'mebel uyda'
 'сотувчи/тикувчи' 'нафакада (сотувчи)' 'кондитер' 'stanokchi' 'malyar'
 'artist' 'chakana savdogar' 'гузаллик салони ишчиси' 'булим рахбари'
 'нафaкада' 'рахбар' 'afitsant' 'фаробий савдо комплексида савдогар'
 'savdogar (chakana savdo)' 'to‘quvchi' 'taksi'
 'носир ошхонасида ошхона ишчиси' 'авто электирик' 'винтелация устаси'
 'услубчи' 'davlat ijrochisi' 'сирчи уста' 'хоким ёрдамчиси' 'tayyorlov'
 'новвой' 'дуродгор' 'электр устаси' 'xamir tayyorlaydi' 'уста , хайдовчи'
 'elektrik' 'атг ходими' 'shafyor' 'usta (issiqxonasi mavjud)'
 'мебел тамирловчи уста' 'сут катик сотишади' 'хусусий амалиёт'
 'ish yurutuvchi' 'ustachilik' 'chevar tikuvchi' 'buyurtmachi' 'taksis'
 'qoravul' 'повор ошпаз' 'tarozichi' 'payvandchi'
 'аёллар оёк кийимлари сотади' 'уста (эшик-ром)' 'мехмонхона бошкарувчиси'
 'чорвачи' 'otdelkachi' 'тозаловчи' 'савдогарр' 'tikuvchilik'
 'кадрлар бўлими мутахасиси' 'kosib' 'тикувчи (хунарманд)'
 'туман худудида' 'нафакада(сотувчи)' 'mavsumiy ishchi' 'operator'
 'nafaqa' 'kassir' 'isuzi boshqaruvchisi' 'уста-курувчи' 'мфй раиси'
 'buxgalter' 'damas xaydaydi (taksist)' 'савдода ёдамчи'
 'sotuvchi savdogar' 'boyoq xodimi' 'savdogar (moshina)'
 'тадбиркор куёш батареякаси' 'кореяда заводда ишлайди' 'fermer'
 'дорихона сотувчи' 'chorvachilik bilan' 'хайдовчи(таксист)'
 'pilaramada ishchi' 'xotin qizlar faoli' 'mexanik' 'рус тили укитувчиси'
 'duradgor usta' 'mebel (stol stul)' 'дукон очади' 'oshpaz (shashlukpaz)'
 'дехкон бозорида к/х махсулотлари сотиш' 'xizmat ko‘rsatish (pilorama)'
 'ёрдамчи савдода' 'nafaqada / тикувчи' 'uqituvchi'
 'oylaviy ishlab chiqarish' 'satuvchi' 'мебел ясовчм уста'
 'уйда чеварчилик килиш учун' 'имрон ошхонада эгаси' 'олиб сотади'
 'супурги етиштиради' 'xo‘jalik ishlar mudiri' 'салтарош'
 'мавсумий мева сотади' 'direktor o‘rinbosari' 'nafaqada / sotuvchi'
 'savdoda ytordamchi' 'учкуприк тумани' 'мева сотади' 'репитотор'
 'электрик' 'usta quruvchi' 'yoshlar yetakchisi' 'undiruv mutaxassisi'
 'фермер' 'авто устаси' 'иш ютирувчи' 'moyshik' 'кичик тиббий ходим'
 'kontrolchi' 'тракторчи' 'pensioner' 'кондитер ёрдамчиси'
 'сотувчи мавсумий мевалар сотади' 'somsapaz' 'савдага ёрдамчи'
 'mini osh xona' 'uyda chorvachilik bilan shug‘ullanadi'
 'xonadonida chorvachilik bilan shug‘ullanadi' 'компьютер устаси'
 'телефон устаси' 'quruvchi' 'шеф повур' 'oshxona' 'nafaqada / tikuvchi'
 'сантехник' 'manikyurchi' 'nafaqada / dexqon' 'нафакхур'
 'беморларга караш' 'иш бошкарувчи' 'unicon-soft да туман рахбари'
 'бармен' 'avtomabil usta' 'shifokor' 'пенсионер ва савдогар' 'коровул'
 'santexnik' 'fotostudiya' 'дехкон молбокар' 'savdoqar' 'kuruvchi usta'
 'avtomobil ustasi' 'ingliz tilidan dars beradi' 'уйда курпа тушак килади'
 'товар олди сотти' 'shashlikpaz' 'baxor bolajon bog‘chada buxgalter'
 'kafel ustasi' 'osgpaz' 'курувчи уста  ва таксист' 'савдогар трикотож'
 'уста ва таксист' 'novvoy' 'nonvoy va haydovchi'
 'хизмат курсатиш шашликпаз' 'директор' 'нафакада (дехкон)'
 'савдогар ёйма' 'салон аёлларга хизмат курсатиш'
 'юкори синф математика укитувчи' 'курувчи' 'савдо дукон' 'хунарманд'
 'xaydov traktor xaydaydi' 'ппхб' 'xususiy emakxona' 'жахон бозорда савдо'
 'jismoniy shahslarga murakkab bo‘lmagan qurilish-tamirlash ishlar'
 'укитувчм' 'доришунос' 'маляр устаси' 'oshxona ishchisi'
 'дехкон хужалиги' 'богдорчилик фермасида ишчи' 'aptekada sotuvchi'
 'потуг поликлиникада коровул ва махаллани повури' '?оровул' 'ёг догловчи'
 'дехкончилик учун' 'уста (маиший техник)' 'kompyuter ustasi' 'баликчи'
 'uy bekasi' 'ayollar ro‘moli sotuvchisi' 'тасвирчи' 'богчада тарбиячи'
 'асалчи' 'dispecher' 'олий тоифали хамшира' 'sex raxbari'
 'ипотека банкда коровул' 'gandbol murabbiyi' 'сомса пиширади' 'нафвкада'
 'дехкон бозолрлрда к/х меваларини сотиш' 'уста автомобил' 'дупидуз'
 'navbatchi' 'akfa o‘rnatuvchi' 'савдогар(онлайн дукон)'
 'савдогар(гушт махсулотлари)' 'савдода' 'иш бошкорувчи' 'мтм'
 'savdodas yordamchi' 'savododa yordamchi' 'тукувчи' 'дизайнер'
 'вейзажист(ишчи)' 'стоматолог' 'механизатор' 'оддий ишчи'
 'кондитор махсулоти ишлаб чикаради' 'ichchi xodim' 'уста сантехник'
 'тикувчи хунарманд' 'чорва молларини етиштириш' 'qutqaruvchi'
 'чодак икватрял мчж' 'савдогар сочик дастурхон' 'машина уста'
 'моляр устаси' 'болаларга караб туриш' '?урквчи уста' 'musiqa murabbiy'
 'биринчи уринбосар йордамчиси' 'дехкон бозорида к/х махсулотларини сотиш'
 'rahbar' 'yog‘och memorchiligi' 'авто уста' 'konditer' 'мутахасис'
 'техник' 'tadbirkor oshpaz' 'у?итувчи' 'хайдовчи тасист' 'коравул'
 'suvchi' 'мебель устаси' 'hunarmandchilik' 'рахбар уринбосари'
 'taxlovchi' 'doimiy ishchi' 'чарвадор' 'стилист' 'chorva'
 'oshpaz somsapaz' 'ёш болалар масажчиси' 'шифохона' 'акфа ишлаб чикаради'
 'савдога ёрджамчи' 'темирчи уста' 'чигит сехи ишчиси' 'sanatkor'
 'хусусий тарбиячи' 'катта оператор' 'administrator' '1' 'xarbiy'
 'usta bo‘yoqchi' 'хисобчи' 'туникасоз' 'ishchi xodim' 'садода ёрдамчи'
 'кандолат махсулотлари' 'svarka ustasi' 'adelka' 'mutaxasis'
 'атлас ва адрас тукиш' 'савдодла ёрдамчи' 'акфа уста'
 'репититорлик хизмати' 'эликтерик' 'кутубхон' 'dehqonchilik' 'тикуви'
 'иссикхона махсулотларини етиштириш' 'payvantchi usta' 'svarshik usta'
 'musiqachi' 'mehmonhonada adminstrator' 'ёшлар ишлар агентлиги етакчи'
 'idish yuvuvchi' 'экскаватор хайдовчиси' 'xizmat korsatish'
 'бокувчи (чорва)' 'тикуш бичиш' 'fermer xo‘jaligi' 'usta-quruvchi'
 'xamshira' 'дехкон супурги етиштиради' 'устачилик' 'уста ва нонвой'
 'chorva boqadi' 'hazinabon' 'чеварчилик' 'маиший техникаларни жихозловчи'
 'елхон мфй' 'nonvoychilik' 'yollanma ishchi' 'ёрдамчи ишчи'
 'дарвоза уста' 'parranda boqadi' 'мошина олиб сотар' 'хусусий оператор'
 'santexnik usta' 'meva oldi sotdisi bilan shug‘illanadi' 'dehqon']

In [42]:
selected['образование'].value_counts()

образование
среднее                2103
средне-специальное     1032
nan                     321
высшее                  128
неоконченное высшее      45
среднее_x000d_           41
урта махсус               1
урта-махсус               1
начальное                 1
Name: count, dtype: int64

In [43]:
selected['образование'] = selected['образование'].replace({
        'nan': 'урта махсус '
    })

In [44]:
import re
def clean_text_columns_strict(df, columns):
    
    for col in columns:
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value).astype(str).str.lower()
        df[col] = df[col].apply(lambda x: re.sub(r'[^a-zа-яё0-9\s]', '', x))
        df[col] = df[col].str.replace(r'\s+', ' ', regex=True).str.strip()

    return df

In [45]:
selected = clean_text_columns_strict(selected, ['образование', 'должность'])

In [46]:
selected["образование"].value_counts()

образование
среднее                2103
среднеспециальное      1032
урта махсус             322
высшее                  128
неоконченное высшее      45
среднееx000d             41
уртамахсус                1
начальное                 1
Name: count, dtype: int64

In [47]:
selected['образование'] = selected['образование'].replace({
    'уртамахсус': 'среднее',
    'урта': 'среднее',
    'урта махсус': 'среднее',
    'среднее_x000d_\n': 'среднее',
    'xususiy amaliyot': 'другое',
    'неоконченное высшее': 'высшее',
    'среднеспециальное': 'среднее',
    'среднееx000d': 'среднее',
    'средне': 'среднее',
    'среднее_x000d_': 'среднее',
    'o‘qituvchi 25-maktab': 'высшее',
    'nan': 'начальное',
    'неоконченное высшее': 'высшее'

})

In [48]:
selected['образование'].value_counts()

образование
среднее      3499
высшее        173
начальное       1
Name: count, dtype: int64

In [49]:
selected.dropna(subset=["образование"], inplace=True)

In [50]:
selected["должность"].value_counts()

должность
nan                 488
тикувчи             281
савдогар            175
хайдовчи            170
уста                118
                   ...
кондитер              1
нафакада сотувчи      1
сотувчитикувчи        1
mebel uyda            1
dehqon                1
Name: count, Length: 571, dtype: int64

In [51]:
selected['должность'] = selected['должность'].replace({
    'nan': 'уста',
})

In [52]:
selected["должность"].value_counts()

должность
уста                606
тикувчи             281
савдогар            175
хайдовчи            170
sotuvchi            105
                   ...
кондитер              1
нафакада сотувчи      1
сотувчитикувчи        1
mebel uyda            1
dehqon                1
Name: count, Length: 570, dtype: int64

In [53]:
selected.dropna(subset=["должность"], inplace=True)

In [54]:
df_cleaned = selected.copy(deep=True)
df_cleaned.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,область \город,регион \город,количество членов семьи,образование,должность,is_bad_client,year
0,2023-08-11,NaN,5000000.0,3746309.4,12.0,1.0,миграция,72.0,47.0,м,фаргона вилояти,узбекистон тумани,NaN,среднее,уста,True,2023
1,2023-09-05,NaN,5000000.0,4580890.3,12.0,1.0,миграция,72.0,28.0,м,фаргона вилояти,фуркат тумани,NaN,среднее,уста,True,2023
2,2023-08-18,NaN,4000000.0,478947.03,12.0,1.0,миграция,72.0,30.0,ж,фаргона вилояти,узбекистон тумани,1.0,среднее,богбон,True,2023
3,2023-09-04,NaN,5000000.0,319060.65,12.0,1.0,миграция,72.0,40.0,м,фаргона вилояти,кува тумани,1.0,среднее,шифокор,True,2023
4,2023-09-13,NaN,4000000.0,2673022.36,12.0,1.0,миграция,72.0,22.0,м,фаргона вилояти,узбекистон тумани,NaN,среднее,уста,True,2023

In [55]:
df_cleaned['количество членов семьи'].isna().sum()

56

In [56]:
mode_value = df_cleaned['количество членов семьи'].mode()[0]
df_cleaned['количество членов семьи'] = df_cleaned['количество членов семьи'].fillna(mode_value)

In [57]:
df_cleaned['семейное положение'] = np.where(df_cleaned['количество членов семьи'] == 1, 'single', 'married')

In [58]:
df_cleaned.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,область \город,регион \город,количество членов семьи,образование,должность,is_bad_client,year
0,2023-08-11,married,5000000.0,3746309.4,12.0,1.0,миграция,72.0,47.0,м,фаргона вилояти,узбекистон тумани,4.0,среднее,уста,True,2023
1,2023-09-05,married,5000000.0,4580890.3,12.0,1.0,миграция,72.0,28.0,м,фаргона вилояти,фуркат тумани,4.0,среднее,уста,True,2023
2,2023-08-18,single,4000000.0,478947.03,12.0,1.0,миграция,72.0,30.0,ж,фаргона вилояти,узбекистон тумани,1.0,среднее,богбон,True,2023
3,2023-09-04,single,5000000.0,319060.65,12.0,1.0,миграция,72.0,40.0,м,фаргона вилояти,кува тумани,1.0,среднее,шифокор,True,2023
4,2023-09-13,married,4000000.0,2673022.36,12.0,1.0,миграция,72.0,22.0,м,фаргона вилояти,узбекистон тумани,4.0,среднее,уста,True,2023

In [59]:
df_cleaned['is_bad_client'].value_counts()

is_bad_client
False    3289
True      384
Name: count, dtype: int64

In [60]:
df_cleaned['is_bad_client'] = df_cleaned['is_bad_client'].astype(int)

In [61]:
df_cleaned.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,область \город,регион \город,количество членов семьи,образование,должность,is_bad_client,year
0,2023-08-11,married,5000000.0,3746309.4,12.0,1.0,миграция,72.0,47.0,м,фаргона вилояти,узбекистон тумани,4.0,среднее,уста,1,2023
1,2023-09-05,married,5000000.0,4580890.3,12.0,1.0,миграция,72.0,28.0,м,фаргона вилояти,фуркат тумани,4.0,среднее,уста,1,2023
2,2023-08-18,single,4000000.0,478947.03,12.0,1.0,миграция,72.0,30.0,ж,фаргона вилояти,узбекистон тумани,1.0,среднее,богбон,1,2023
3,2023-09-04,single,5000000.0,319060.65,12.0,1.0,миграция,72.0,40.0,м,фаргона вилояти,кува тумани,1.0,среднее,шифокор,1,2023
4,2023-09-13,married,4000000.0,2673022.36,12.0,1.0,миграция,72.0,22.0,м,фаргона вилояти,узбекистон тумани,4.0,среднее,уста,1,2023

In [62]:
df_cleaned.isna().sum()

дата выдачи                0
семейное положение         0
сумма выдачи               0
остаток суммы              0
срок кредита (месяц)       0
цикл                       0
цель кредита               0
процентная ставка          0
возраст                    0
пол                        0
область \город             0
регион \город              0
количество членов семьи    0
образование                0
должность                  0
is_bad_client              0
year                       0
dtype: int64

In [63]:
import requests

unique_years = df_cleaned['year'].unique()

#year_to_rate mapping
year_to_rate = {}

for year in unique_years:
    date_str = f"{year}-02-01"
    url = f"https://cbu.uz/uz/arkhiv-kursov-valyut/json/all/{date_str}/"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        for item in data:
            if item['Ccy'] == 'USD':
                year_to_rate[year] = int(float(item['Rate']))
                break
    else:
        year_to_rate[year] = None 


df_cleaned['usd_rate'] = df_cleaned['year'].map(year_to_rate)

In [64]:
df_cleaned['область \город'].value_counts()

область \город
фаргона вилояти     1773
наманган вилояти    1516
андижон вилояти      381
тошкент шахри          2
тошкент вилояти        1
Name: count, dtype: int64

In [66]:
shaped_bread_prices = {
    'фаргона вилояти': 2650,
    'наманган вилояти': 2700,
    'андижон вилояти': 2700,
    'тошкент шахри': 2800,
    'тошкент вилояти': 2800
}

cottonseed_oil_prices = {
    'фаргона вилояти': 19750,
    'наманган вилояти': 17100,
    'андижон вилояти': 18500,
    'тошкент шахри': 18250,
    'тошкент вилояти': 18250
}

beef_prices = {
    'фаргона вилояти': 77000,
    'наманган вилояти': 76000,
    'андижон вилояти': 82500,
    'тошкент шахри': 85000,
    'тошкент вилояти': 85000
}

In [67]:
df_cleaned['shaped_bread(som)'] = df_cleaned['область \\город'].map(shaped_bread_prices)
df_cleaned['cottonseed oil(som)'] = df_cleaned['область \\город'].map(cottonseed_oil_prices)
df_cleaned['beef(som)'] = df_cleaned['область \\город'].map(beef_prices)

In [68]:
df_cleaned.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,...,регион \город,количество членов семьи,образование,должность,is_bad_client,year,usd_rate,shaped_bread(som),cottonseed oil(som),beef(som)
0,2023-08-11,married,5000000.0,3746309.4,12.0,1.0,миграция,72.0,47.0,м,...,узбекистон тумани,4.0,среднее,уста,1,2023,11269,2650,19750,77000
1,2023-09-05,married,5000000.0,4580890.3,12.0,1.0,миграция,72.0,28.0,м,...,фуркат тумани,4.0,среднее,уста,1,2023,11269,2650,19750,77000
2,2023-08-18,single,4000000.0,478947.03,12.0,1.0,миграция,72.0,30.0,ж,...,узбекистон тумани,1.0,среднее,богбон,1,2023,11269,2650,19750,77000
3,2023-09-04,single,5000000.0,319060.65,12.0,1.0,миграция,72.0,40.0,м,...,кува тумани,1.0,среднее,шифокор,1,2023,11269,2650,19750,77000
4,2023-09-13,married,4000000.0,2673022.36,12.0,1.0,миграция,72.0,22.0,м,...,узбекистон тумани,4.0,среднее,уста,1,2023,11269,2650,19750,77000

In [69]:
df_cleaned['сумма_выдачи(usd)'] = (df_cleaned['сумма выдачи'] / df_cleaned['usd_rate']).astype(int)
df_cleaned['остаток_суммы(usd)'] = (df_cleaned['остаток суммы'] / df_cleaned['usd_rate']).astype(int)

In [70]:
df_cleaned.head()

,дата выдачи,семейное положение,сумма выдачи,остаток суммы,срок кредита (месяц),цикл,цель кредита,процентная ставка,возраст,пол,...,образование,должность,is_bad_client,year,usd_rate,shaped_bread(som),cottonseed oil(som),beef(som),сумма_выдачи(usd),остаток_суммы(usd)
0,2023-08-11,married,5000000.0,3746309.4,12.0,1.0,миграция,72.0,47.0,м,...,среднее,уста,1,2023,11269,2650,19750,77000,443,332
1,2023-09-05,married,5000000.0,4580890.3,12.0,1.0,миграция,72.0,28.0,м,...,среднее,уста,1,2023,11269,2650,19750,77000,443,406
2,2023-08-18,single,4000000.0,478947.03,12.0,1.0,миграция,72.0,30.0,ж,...,среднее,богбон,1,2023,11269,2650,19750,77000,354,42
3,2023-09-04,single,5000000.0,319060.65,12.0,1.0,миграция,72.0,40.0,м,...,среднее,шифокор,1,2023,11269,2650,19750,77000,443,28
4,2023-09-13,married,4000000.0,2673022.36,12.0,1.0,миграция,72.0,22.0,м,...,среднее,уста,1,2023,11269,2650,19750,77000,354,237

In [71]:
df_cleaned.to_csv("../RnD/df_6month_60difference.csv", index=False)
# df_cleaned.to_csv("df2307.csv", index=False)