In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../dataset/toyona_gold_bnpl.csv")
df.head()

,ID Клиента,Дата рождения,Пол,Семейное положение,Уровень образования,Количество иждивенцев,Профессия,Наличие Авто,Собственное жилье,Залог,...,Активные кредиты,Первоначальный взнос,Наличие карты,Сумма просрочки,Количество активных просроченных дней,Количество Кумулятивной просрочки,Филиал,Дата Выдачи,Дата окончания,Название Продукта
0,9279,1989-07-07,male,Женат/Замужем,,3,oqituvchi,,,,...,1,0,Нет,0,0,0,Turkiston,2025-09-10,2026-08-10,A40395
1,9278,1991-06-14,female,Женат/Замужем,,3,ishchi,,,,...,1,0,Да,0,0,0,Turkiston,2025-09-09,2026-08-09,A400000156
2,7496,1992-09-03,female,Женат/Замужем,,0,ISHCHI,,,,...,1,0,Нет,0,0,0,Navoiy,2025-09-09,2026-08-09,A400000092
3,9270,1991-08-23,female,Женат/Замужем,,3,tarbiyachi,,,,...,1,0,Да,176542,1,1,Navoiy,2025-08-09,2026-07-09,бугдой
4,9267,1953-07-25,female,Женат/Замужем,,4,nafaqa,,,,...,1,0,Да,0,0,0,Navoiy,2025-09-08,2026-08-08,K102195

In [4]:
df.isna().sum()

ID Клиента                                          0
 Дата рождения                                      0
 Пол                                                0
 Семейное положение                                 0
 Уровень образования                                0
 Количество иждивенцев                              0
 Профессия                                          0
 Наличие Авто                                       0
 Собственное жилье                                  0
 Залог                                              0
 Статус клиента                                     0
 Зарплата                                           0
 Сумма Кредита                                      0
 Ежемесячное погашение по графику                   0
 Активные кредиты                                   0
 Первоначальный взнос                               0
 Наличие карты                                      0
 Сумма просрочки                                    0
 Количество активных просроченных дней              0
 Количество Кумулятивной просрочки                  0
 Филиал                                             0
 Дата Выдачи                                        0
 Дата окончания                                     0
 Название Продукта                                  0
dtype: int64

In [5]:
df.columns = [col.lower() for col in df.columns]

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df_copy = df.copy()
df_copy.columns

Index(['id клиента', 'дата рождения', 'пол', 'семейное положение',
       'уровень образования', 'количество иждивенцев', 'профессия',
       'наличие авто', 'собственное жилье', 'залог', 'статус клиента',
       'зарплата', 'сумма кредита', 'ежемесячное погашение по графику',
       'активные кредиты', 'первоначальный взнос', 'наличие карты',
       'сумма просрочки', 'количество активных просроченных дней',
       'количество кумулятивной просрочки', 'филиал', 'дата выдачи',
       'дата окончания', 'название продукта'],
      dtype='object')

In [8]:
df_copy.drop(['id клиента', 'уровень образования', 'наличие авто', 'собственное жилье', 'залог'], axis=1, inplace=True)

In [9]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1989-07-07,male,Женат/Замужем,3,oqituvchi,Активный,3800000,3746724,312227,1,0,Нет,0,0,0,Turkiston,2025-09-10,2026-08-10,A40395
1,1991-06-14,female,Женат/Замужем,3,ishchi,Активный,4000000,4925970,410497,1,0,Да,0,0,0,Turkiston,2025-09-09,2026-08-09,A400000156
2,1992-09-03,female,Женат/Замужем,0,ISHCHI,Активный,3000003,3000364,250030,1,0,Нет,0,0,0,Navoiy,2025-09-09,2026-08-09,A400000092
3,1991-08-23,female,Женат/Замужем,3,tarbiyachi,Активный,3300000,2597329,216444,1,0,Да,176542,1,1,Navoiy,2025-08-09,2026-07-09,бугдой
4,1953-07-25,female,Женат/Замужем,4,nafaqa,Активный,2700000,7550547,629212,1,0,Да,0,0,0,Navoiy,2025-09-08,2026-08-08,K102195

In [10]:
df_copy['семейное положение'].value_counts()

 Женат/Замужем         610
 Холост/Не замужем      50
Name: семейное положение, dtype: int64

In [11]:
df_copy = df_copy.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [12]:
df_copy.loc[(df_copy['пол'] == 'male') & (df_copy['семейное положение'] == 'Женат/Замужем'), 'семейное положение'] = 'женат'
df_copy.loc[(df_copy['пол'] == 'female') & (df_copy['семейное положение'] == 'Женат/Замужем'), 'семейное положение'] = 'замужем'

df_copy.loc[(df_copy['пол'] == 'male') & (df_copy['семейное положение'] == 'Холост/Не замужем'), 'семейное положение'] = 'холост'
df_copy.loc[(df_copy['пол'] == 'female') & (df_copy['семейное положение'] == 'Холост/Не замужем'), 'семейное положение'] = 'не замужем'

In [13]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1989-07-07,male,женат,3,oqituvchi,Активный,3800000,3746724,312227,1,0,Нет,0,0,0,Turkiston,2025-09-10,2026-08-10,A40395
1,1991-06-14,female,замужем,3,ishchi,Активный,4000000,4925970,410497,1,0,Да,0,0,0,Turkiston,2025-09-09,2026-08-09,A400000156
2,1992-09-03,female,замужем,0,ISHCHI,Активный,3000003,3000364,250030,1,0,Нет,0,0,0,Navoiy,2025-09-09,2026-08-09,A400000092
3,1991-08-23,female,замужем,3,tarbiyachi,Активный,3300000,2597329,216444,1,0,Да,176542,1,1,Navoiy,2025-08-09,2026-07-09,бугдой
4,1953-07-25,female,замужем,4,nafaqa,Активный,2700000,7550547,629212,1,0,Да,0,0,0,Navoiy,2025-09-08,2026-08-08,K102195

In [14]:
df_copy['семейное положение'].value_counts()

замужем       472
женат         138
холост         27
не замужем     23
Name: семейное положение, dtype: int64

In [15]:
for col in df_copy.select_dtypes(include=['object']).columns:
    df_copy[col] = df_copy[col].astype(str).str.strip().str.lower()

In [16]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1989-07-07,male,женат,3,oqituvchi,активный,3800000,3746724,312227,1,0,нет,0,0,0,turkiston,2025-09-10,2026-08-10,a40395
1,1991-06-14,female,замужем,3,ishchi,активный,4000000,4925970,410497,1,0,да,0,0,0,turkiston,2025-09-09,2026-08-09,a400000156
2,1992-09-03,female,замужем,0,ishchi,активный,3000003,3000364,250030,1,0,нет,0,0,0,navoiy,2025-09-09,2026-08-09,a400000092
3,1991-08-23,female,замужем,3,tarbiyachi,активный,3300000,2597329,216444,1,0,да,176542,1,1,navoiy,2025-08-09,2026-07-09,бугдой
4,1953-07-25,female,замужем,4,nafaqa,активный,2700000,7550547,629212,1,0,да,0,0,0,navoiy,2025-09-08,2026-08-08,k102195

In [17]:
df_copy['профессия'].value_counts()

nafaqa                      106
savdogar                     58
tikuvchi                     48
ishchi                       38
uy bekasi                    31
                           ...
nafaqa 920 ming savdogar      1
nafaqada   farrosh            1
savdogar   nafaqada           1
chevar tikuvchi               1
hr                            1
Name: профессия, Length: 187, dtype: int64

In [18]:
df_copy['профессия'] = df_copy['профессия'].str.strip().str.split().str.join(' ')

In [19]:
df_copy['профессия'].value_counts()

nafaqa                      106
savdogar                     58
tikuvchi                     48
ishchi                       38
uy bekasi                    31
                           ...
nafaqa 920 ming savdogar      1
nafaqada farrosh              1
savdogar nafaqada             1
chevar tikuvchi               1
hr                            1
Name: профессия, Length: 187, dtype: int64

In [20]:
df_copy['количество кумулятивной просрочки'].value_counts()

0     459
1     107
2      34
3      13
4      10
8       7
5       6
12      6
6       5
9       4
11      4
10      3
7       2
Name: количество кумулятивной просрочки, dtype: int64

In [21]:
def replace_product_name(name: str):
    if not isinstance(name, str) or name == "":
        return "кольцо"
    
    first = name.strip()[0].lower()
    if first == "а" or first == "a":
        return "кулон"
    elif first == "к" or first == "k":
        return "комплект"
    elif first == "м" or first == "m" or first == "m":
        return "цепочка"
    elif first == "e":
        return "серьги"
    elif first == "r":
        return "кольцо"
    elif first.isalpha():
        return name.strip()
    else:
        return "кольцо"

In [22]:
df_copy["название продукта"] = df_copy["название продукта"].apply(replace_product_name)

In [23]:
df_copy['название продукта'].value_counts()

кулон       425
комплект    177
кольцо       44
цепочка      10
серьги        2
бугдой        1
цветок        1
Name: название продукта, dtype: int64

In [24]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1989-07-07,male,женат,3,oqituvchi,активный,3800000,3746724,312227,1,0,нет,0,0,0,turkiston,2025-09-10,2026-08-10,кулон
1,1991-06-14,female,замужем,3,ishchi,активный,4000000,4925970,410497,1,0,да,0,0,0,turkiston,2025-09-09,2026-08-09,кулон
2,1992-09-03,female,замужем,0,ishchi,активный,3000003,3000364,250030,1,0,нет,0,0,0,navoiy,2025-09-09,2026-08-09,кулон
3,1991-08-23,female,замужем,3,tarbiyachi,активный,3300000,2597329,216444,1,0,да,176542,1,1,navoiy,2025-08-09,2026-07-09,бугдой
4,1953-07-25,female,замужем,4,nafaqa,активный,2700000,7550547,629212,1,0,да,0,0,0,navoiy,2025-09-08,2026-08-08,комплект

In [25]:
df_copy.dtypes

дата рождения                            object
пол                                      object
семейное положение                       object
количество иждивенцев                    object
профессия                                object
статус клиента                           object
зарплата                                 object
сумма кредита                             int64
ежемесячное погашение по графику          int64
активные кредиты                          int64
первоначальный взнос                      int64
наличие карты                            object
сумма просрочки                           int64
количество активных просроченных дней     int64
количество кумулятивной просрочки         int64
филиал                                   object
дата выдачи                              object
дата окончания                           object
название продукта                        object
dtype: object

In [26]:
df_copy['количество иждивенцев'] = pd.to_numeric(df_copy['количество иждивенцев'], errors='coerce')
df_copy['зарплата'] = pd.to_numeric(df_copy['зарплата'], errors='coerce')


df_copy['дата рождения'] = pd.to_datetime(df_copy['дата рождения'], errors='coerce')
df_copy['дата выдачи'] = pd.to_datetime(df_copy['дата выдачи'], errors='coerce')
df_copy['дата окончания'] = pd.to_datetime(df_copy['дата окончания'], errors='coerce')

In [27]:
df_copy.dtypes

дата рождения                            datetime64[ns]
пол                                              object
семейное положение                               object
количество иждивенцев                           float64
профессия                                        object
статус клиента                                   object
зарплата                                        float64
сумма кредита                                     int64
ежемесячное погашение по графику                  int64
активные кредиты                                  int64
первоначальный взнос                              int64
наличие карты                                    object
сумма просрочки                                   int64
количество активных просроченных дней             int64
количество кумулятивной просрочки                 int64
филиал                                           object
дата выдачи                              datetime64[ns]
дата окончания                           datetime64[ns]
название продукта                                object
dtype: object

In [28]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1989-07-07,male,женат,3.0,oqituvchi,активный,3800000.0,3746724,312227,1,0,нет,0,0,0,turkiston,2025-09-10,2026-08-10,кулон
1,1991-06-14,female,замужем,3.0,ishchi,активный,4000000.0,4925970,410497,1,0,да,0,0,0,turkiston,2025-09-09,2026-08-09,кулон
2,1992-09-03,female,замужем,0.0,ishchi,активный,3000003.0,3000364,250030,1,0,нет,0,0,0,navoiy,2025-09-09,2026-08-09,кулон
3,1991-08-23,female,замужем,3.0,tarbiyachi,активный,3300000.0,2597329,216444,1,0,да,176542,1,1,navoiy,2025-08-09,2026-07-09,бугдой
4,1953-07-25,female,замужем,4.0,nafaqa,активный,2700000.0,7550547,629212,1,0,да,0,0,0,navoiy,2025-09-08,2026-08-08,комплект

In [29]:
today = pd.Timestamp.today().normalize()
df_copy['возраст'] = (today - df_copy['дата рождения']).astype('<m8[Y]')
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта,возраст
0,1989-07-07,male,женат,3.0,oqituvchi,активный,3800000.0,3746724,312227,1,0,нет,0,0,0,turkiston,2025-09-10,2026-08-10,кулон,36.0
1,1991-06-14,female,замужем,3.0,ishchi,активный,4000000.0,4925970,410497,1,0,да,0,0,0,turkiston,2025-09-09,2026-08-09,кулон,34.0
2,1992-09-03,female,замужем,0.0,ishchi,активный,3000003.0,3000364,250030,1,0,нет,0,0,0,navoiy,2025-09-09,2026-08-09,кулон,32.0
3,1991-08-23,female,замужем,3.0,tarbiyachi,активный,3300000.0,2597329,216444,1,0,да,176542,1,1,navoiy,2025-08-09,2026-07-09,бугдой,33.0
4,1953-07-25,female,замужем,4.0,nafaqa,активный,2700000.0,7550547,629212,1,0,да,0,0,0,navoiy,2025-09-08,2026-08-08,комплект,72.0

1 - bad
0 - good

In [30]:
df_copy['is_bad_client'] = (df_copy['количество активных просроченных дней'] >= 60).astype(int)

In [31]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,...,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта,возраст,is_bad_client
0,1989-07-07,male,женат,3.0,oqituvchi,активный,3800000.0,3746724,312227,1,...,нет,0,0,0,turkiston,2025-09-10,2026-08-10,кулон,36.0,0
1,1991-06-14,female,замужем,3.0,ishchi,активный,4000000.0,4925970,410497,1,...,да,0,0,0,turkiston,2025-09-09,2026-08-09,кулон,34.0,0
2,1992-09-03,female,замужем,0.0,ishchi,активный,3000003.0,3000364,250030,1,...,нет,0,0,0,navoiy,2025-09-09,2026-08-09,кулон,32.0,0
3,1991-08-23,female,замужем,3.0,tarbiyachi,активный,3300000.0,2597329,216444,1,...,да,176542,1,1,navoiy,2025-08-09,2026-07-09,бугдой,33.0,0
4,1953-07-25,female,замужем,4.0,nafaqa,активный,2700000.0,7550547,629212,1,...,да,0,0,0,navoiy,2025-09-08,2026-08-08,комплект,72.0,0

In [33]:
df_copy['количество активных просроченных дней'].value_counts()

0      459
31      57
61      18
2        8
7        8
1        8
122      8
5        6
243      6
3        6
153      6
92       5
38       3
8        3
9        3
181      3
37       3
6        3
212      3
33       3
67       2
380      2
334      2
273      2
32       2
4        2
68       2
63       2
274      1
431      1
324      1
65       1
58       1
313      1
342      1
358      1
337      1
307      1
325      1
26       1
41       1
246      1
272      1
36       1
16       1
69       1
237      1
95       1
123      1
159      1
34       1
155      1
488      1
Name: количество активных просроченных дней, dtype: int64

In [34]:
len(df_copy)

660

In [35]:
df_copy['is_bad_client'].value_counts(normalize=True)

0    0.878788
1    0.121212
Name: is_bad_client, dtype: float64

In [36]:
df_copy.columns

Index(['дата рождения', 'пол', 'семейное положение', 'количество иждивенцев',
       'профессия', 'статус клиента', 'зарплата', 'сумма кредита',
       'ежемесячное погашение по графику', 'активные кредиты',
       'первоначальный взнос', 'наличие карты', 'сумма просрочки',
       'количество активных просроченных дней',
       'количество кумулятивной просрочки', 'филиал', 'дата выдачи',
       'дата окончания', 'название продукта', 'возраст', 'is_bad_client'],
      dtype='object')

In [37]:
df_copy['филиал'].value_counts()

turkiston    433
navoiy       222
furqat         5
Name: филиал, dtype: int64

In [38]:
feature_cols = ['возраст', 'пол', 'семейное положение', 'количество иждивенцев',
 'профессия', 'статус клиента', 'зарплата', 'сумма кредита',
 'ежемесячное погашение по графику', 'активные кредиты',
 'первоначальный взнос', 'наличие карты', 'филиал', 'название продукта']

In [39]:
selected = df_copy[feature_cols + ['is_bad_client']].copy()

In [40]:
npl_ratio = selected["is_bad_client"].mean() * 100
print(f"NPL: {npl_ratio:.2f}%")

NPL: 12.12%

In [41]:
selected.head()

,возраст,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,филиал,название продукта,is_bad_client
0,36.0,male,женат,3.0,oqituvchi,активный,3800000.0,3746724,312227,1,0,нет,turkiston,кулон,0
1,34.0,female,замужем,3.0,ishchi,активный,4000000.0,4925970,410497,1,0,да,turkiston,кулон,0
2,32.0,female,замужем,0.0,ishchi,активный,3000003.0,3000364,250030,1,0,нет,navoiy,кулон,0
3,33.0,female,замужем,3.0,tarbiyachi,активный,3300000.0,2597329,216444,1,0,да,navoiy,бугдой,0
4,72.0,female,замужем,4.0,nafaqa,активный,2700000.0,7550547,629212,1,0,да,navoiy,комплект,0

In [52]:
selected.to_csv("../dataset/toyona_gold_cleaned.csv", index=False)