In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../dataset/toyona_gold_mult_products.xlsx")
df.head()

,ID Клиента,Дата рождения,Пол,Семейное положение,Уровень образования,Количество иждивенцев,Профессия,Наличие Авто,Собственное жилье,Залог,...,Наличие карты,Сумма просрочки,Количество активных просроченных дней,Количество Кумулятивной просрочки,Филиал,Дата Выдачи,Дата окончания,Название Продукта,Статус,Дата завершения
0,5647,1976-04-11,female,Женат/Замужем,NaN,2.0,Nonvoy,NaN,NaN,NaN,...,Нет,0,0,0,Navoiy,2025-10-10,2026-09-10,A400205,Активный,NaT
1,2418,1988-03-28,female,Женат/Замужем,NaN,1.0,Tozalik xodimi,NaN,NaN,NaN,...,Нет,0,0,0,Turkiston,2025-10-03,2026-09-03,A400000140,Активный,NaT
2,9521,1991-10-21,female,Женат/Замужем,NaN,2.0,bolalar hamshirasi,NaN,NaN,NaN,...,Нет,0,0,0,Navoiy,2025-10-05,2026-09-05,A40408,Активный,NaT
3,7019,1973-12-04,male,Женат/Замужем,NaN,NaN,Taksist,NaN,NaN,NaN,...,Нет,0,0,0,Turkiston,2025-10-02,2026-09-02,A40398; A400280,Активный,NaT
4,9508,1979-01-10,male,Женат/Замужем,NaN,1.0,katta usta,NaN,NaN,NaN,...,Нет,0,0,0,Navoiy,2025-10-02,2026-09-02,A400000014,Активный,NaT

In [3]:
df.isna().sum()

ID Клиента                                 0
Дата рождения                              9
Пол                                        0
Семейное положение                         0
Уровень образования                      702
Количество иждивенцев                     64
Профессия                                 16
Наличие Авто                             702
Собственное жилье                        702
Залог                                    702
Статус клиента                             0
Зарплата                                  16
Сумма Кредита                              0
Ежемесячное погашение по графику           0
Активные кредиты                           0
Первоначальный взнос                       0
Наличие карты                              0
Сумма просрочки                            0
Количество активных просроченных дней      0
Количество Кумулятивной просрочки          0
Филиал                                     0
Дата Выдачи                                0
Дата окончания                             0
Название Продукта                          0
Статус                                     0
Дата завершения                          555
dtype: int64

In [4]:
df.columns = [col.lower() for col in df.columns]

In [5]:
df.columns = df.columns.str.strip()

In [6]:
df_copy = df.copy()
df_copy.columns

Index(['id клиента', 'дата рождения', 'пол', 'семейное положение',
       'уровень образования', 'количество иждивенцев', 'профессия',
       'наличие авто', 'собственное жилье', 'залог', 'статус клиента',
       'зарплата', 'сумма кредита', 'ежемесячное погашение по графику',
       'активные кредиты', 'первоначальный взнос', 'наличие карты',
       'сумма просрочки', 'количество активных просроченных дней',
       'количество кумулятивной просрочки', 'филиал', 'дата выдачи',
       'дата окончания', 'название продукта', 'статус', 'дата завершения'],
      dtype='object')

In [7]:
df_copy.drop(['id клиента', 'уровень образования', 'наличие авто', 'собственное жилье', 'залог', 'дата завершения', 'статус'], axis=1, inplace=True)

In [8]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1976-04-11,female,Женат/Замужем,2.0,Nonvoy,Активный,2000000.0,15232757,1269396,2,0,Нет,0,0,0,Navoiy,2025-10-10,2026-09-10,A400205
1,1988-03-28,female,Женат/Замужем,1.0,Tozalik xodimi,Активный,3500000.0,4496189,374682,2,0,Нет,0,0,0,Turkiston,2025-10-03,2026-09-03,A400000140
2,1991-10-21,female,Женат/Замужем,2.0,bolalar hamshirasi,Активный,1500000.0,3566595,297216,1,0,Нет,0,0,0,Navoiy,2025-10-05,2026-09-05,A40408
3,1973-12-04,male,Женат/Замужем,NaN,Taksist,Активный,4000000.0,7544792,628732,2,0,Нет,0,0,0,Turkiston,2025-10-02,2026-09-02,A40398; A400280
4,1979-01-10,male,Женат/Замужем,1.0,katta usta,Активный,4000000.0,4608685,384057,1,0,Нет,0,0,0,Navoiy,2025-10-02,2026-09-02,A400000014

In [9]:
df_copy['семейное положение'].value_counts()

Женат/Замужем        649
Холост/Не замужем     53
Name: семейное положение, dtype: int64

In [10]:
df_copy = df_copy.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [11]:
df_copy.loc[(df_copy['пол'] == 'male') & (df_copy['семейное положение'] == 'Женат/Замужем'), 'семейное положение'] = 'женат'
df_copy.loc[(df_copy['пол'] == 'female') & (df_copy['семейное положение'] == 'Женат/Замужем'), 'семейное положение'] = 'замужем'

df_copy.loc[(df_copy['пол'] == 'male') & (df_copy['семейное положение'] == 'Холост/Не замужем'), 'семейное положение'] = 'холост'
df_copy.loc[(df_copy['пол'] == 'female') & (df_copy['семейное положение'] == 'Холост/Не замужем'), 'семейное положение'] = 'не замужем'

In [12]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1976-04-11,female,замужем,2.0,Nonvoy,Активный,2000000.0,15232757,1269396,2,0,Нет,0,0,0,Navoiy,2025-10-10,2026-09-10,A400205
1,1988-03-28,female,замужем,1.0,Tozalik xodimi,Активный,3500000.0,4496189,374682,2,0,Нет,0,0,0,Turkiston,2025-10-03,2026-09-03,A400000140
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,Активный,1500000.0,3566595,297216,1,0,Нет,0,0,0,Navoiy,2025-10-05,2026-09-05,A40408
3,1973-12-04,male,женат,NaN,Taksist,Активный,4000000.0,7544792,628732,2,0,Нет,0,0,0,Turkiston,2025-10-02,2026-09-02,A40398; A400280
4,1979-01-10,male,женат,1.0,katta usta,Активный,4000000.0,4608685,384057,1,0,Нет,0,0,0,Navoiy,2025-10-02,2026-09-02,A400000014

In [13]:
df_copy['семейное положение'].value_counts()

замужем       506
женат         143
холост         28
не замужем     25
Name: семейное положение, dtype: int64

In [14]:
for col in df_copy.select_dtypes(include=['object']).columns:
    df_copy[col] = df_copy[col].astype(str).str.strip().str.lower()

In [15]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1976-04-11,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,0,нет,0,0,0,navoiy,2025-10-10,2026-09-10,a400205
1,1988-03-28,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,0,нет,0,0,0,turkiston,2025-10-03,2026-09-03,a400000140
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,0,нет,0,0,0,navoiy,2025-10-05,2026-09-05,a40408
3,1973-12-04,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,0,нет,0,0,0,turkiston,2025-10-02,2026-09-02,a40398; a400280
4,1979-01-10,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,0,нет,0,0,0,navoiy,2025-10-02,2026-09-02,a400000014

In [16]:
df_copy['профессия'].value_counts()

nafaqa                                             116
savdogar                                            59
tikuvchi                                            52
ishchi                                              41
uy bekasi                                           32
                                                  ...
usta tadbirkor bozorchi                              1
ijarachi                                             1
nafaqa 2 mln + 2 mln tovon puli kalish zavoddan      1
nafaqa bolalar puli                                  1
hr                                                   1
Name: профессия, Length: 194, dtype: int64

In [17]:
df_copy['профессия'] = df_copy['профессия'].str.strip().str.split().str.join(' ')

In [18]:
df_copy['профессия'].value_counts()

nafaqa                                             116
savdogar                                            59
tikuvchi                                            52
ishchi                                              41
uy bekasi                                           32
                                                  ...
usta tadbirkor bozorchi                              1
ijarachi                                             1
nafaqa 2 mln + 2 mln tovon puli kalish zavoddan      1
nafaqa bolalar puli                                  1
hr                                                   1
Name: профессия, Length: 194, dtype: int64

In [19]:
df_copy['количество кумулятивной просрочки'].value_counts()

0      138
1       19
2       16
8       16
24      13
      ...
378      1
237      1
137      1
235      1
467      1
Name: количество кумулятивной просрочки, Length: 229, dtype: int64

In [20]:
def replace_product_name(name: str):
    if not isinstance(name, str) or name.strip() == "":
        return "кольцо"

    parts = [part.strip() for part in name.split(";") if part.strip()]

    def map_single(n: str):
        first = n[0].lower()
        if first in ["а", "a"]:
            return "кулон"
        elif first in ["к", "k"]:
            return "комплект"
        elif first in ["м", "m"]:
            return "цепочка"
        elif first == "e":
            return "серьги"
        elif first == "r":
            return "кольцо"
        elif first.isalpha():
            return n
        else:
            return "кольцо"
        
    return "; ".join(map(map_single, parts))

In [21]:
df_copy["название продукта"] = df_copy["название продукта"].apply(replace_product_name)

In [22]:
df_copy['название продукта'].value_counts()

кулон                          380
комплект                       176
кулон; кулон                    50
кольцо                          31
комплект; кулон                 11
кулон; комплект                 10
кольцо; кулон                   10
цепочка                          7
кулон; кольцо                    6
кулон; кулон; кулон              5
цепочка; кулон                   2
серьги                           2
комплект; кулон; кулон           1
кулон; комплект; кулон           1
кулон; цветок                    1
бугдой                           1
кулон; цепочка                   1
цепочка; кулон; кулон            1
кольцо; кулон; кулон; кулон      1
кулон; кулон; кулон; кулон       1
комплект; кулон; кольцо          1
кольцо; кольцо                   1
кольцо; кулон; кулон             1
цветок                           1
Name: название продукта, dtype: int64

In [23]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1976-04-11,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,0,нет,0,0,0,navoiy,2025-10-10,2026-09-10,кулон
1,1988-03-28,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,0,нет,0,0,0,turkiston,2025-10-03,2026-09-03,кулон
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,0,нет,0,0,0,navoiy,2025-10-05,2026-09-05,кулон
3,1973-12-04,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,0,нет,0,0,0,turkiston,2025-10-02,2026-09-02,кулон; кулон
4,1979-01-10,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,0,нет,0,0,0,navoiy,2025-10-02,2026-09-02,кулон

In [24]:
df_copy.dtypes

дата рождения                            datetime64[ns]
пол                                              object
семейное положение                               object
количество иждивенцев                           float64
профессия                                        object
статус клиента                                   object
зарплата                                        float64
сумма кредита                                     int64
ежемесячное погашение по графику                  int64
активные кредиты                                  int64
первоначальный взнос                              int64
наличие карты                                    object
сумма просрочки                                   int64
количество активных просроченных дней             int64
количество кумулятивной просрочки                 int64
филиал                                           object
дата выдачи                              datetime64[ns]
дата окончания                           datetime64[ns]
название продукта                                object
dtype: object

In [25]:
df_copy['количество иждивенцев'] = pd.to_numeric(df_copy['количество иждивенцев'], errors='coerce')
df_copy['зарплата'] = pd.to_numeric(df_copy['зарплата'], errors='coerce')


df_copy['дата рождения'] = pd.to_datetime(df_copy['дата рождения'], errors='coerce')
df_copy['дата выдачи'] = pd.to_datetime(df_copy['дата выдачи'], errors='coerce')
df_copy['дата окончания'] = pd.to_datetime(df_copy['дата окончания'], errors='coerce')

In [26]:
df_copy.dtypes

дата рождения                            datetime64[ns]
пол                                              object
семейное положение                               object
количество иждивенцев                           float64
профессия                                        object
статус клиента                                   object
зарплата                                        float64
сумма кредита                                     int64
ежемесячное погашение по графику                  int64
активные кредиты                                  int64
первоначальный взнос                              int64
наличие карты                                    object
сумма просрочки                                   int64
количество активных просроченных дней             int64
количество кумулятивной просрочки                 int64
филиал                                           object
дата выдачи                              datetime64[ns]
дата окончания                           datetime64[ns]
название продукта                                object
dtype: object

In [27]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта
0,1976-04-11,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,0,нет,0,0,0,navoiy,2025-10-10,2026-09-10,кулон
1,1988-03-28,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,0,нет,0,0,0,turkiston,2025-10-03,2026-09-03,кулон
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,0,нет,0,0,0,navoiy,2025-10-05,2026-09-05,кулон
3,1973-12-04,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,0,нет,0,0,0,turkiston,2025-10-02,2026-09-02,кулон; кулон
4,1979-01-10,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,0,нет,0,0,0,navoiy,2025-10-02,2026-09-02,кулон

In [28]:
today = pd.Timestamp.today().normalize()
df_copy['возраст'] = (today - df_copy['дата рождения']).astype('<m8[Y]')
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта,возраст
0,1976-04-11,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,0,нет,0,0,0,navoiy,2025-10-10,2026-09-10,кулон,49.0
1,1988-03-28,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,0,нет,0,0,0,turkiston,2025-10-03,2026-09-03,кулон,37.0
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,0,нет,0,0,0,navoiy,2025-10-05,2026-09-05,кулон,33.0
3,1973-12-04,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,0,нет,0,0,0,turkiston,2025-10-02,2026-09-02,кулон; кулон,51.0
4,1979-01-10,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,0,нет,0,0,0,navoiy,2025-10-02,2026-09-02,кулон,46.0

1 - bad
0 - good

In [29]:
df_copy['is_bad_client'] = (df_copy['количество активных просроченных дней'] >= 60).astype(int)

In [30]:
df_copy.head()

,дата рождения,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,...,наличие карты,сумма просрочки,количество активных просроченных дней,количество кумулятивной просрочки,филиал,дата выдачи,дата окончания,название продукта,возраст,is_bad_client
0,1976-04-11,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,...,нет,0,0,0,navoiy,2025-10-10,2026-09-10,кулон,49.0,0
1,1988-03-28,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,...,нет,0,0,0,turkiston,2025-10-03,2026-09-03,кулон,37.0,0
2,1991-10-21,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,...,нет,0,0,0,navoiy,2025-10-05,2026-09-05,кулон,33.0,0
3,1973-12-04,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,...,нет,0,0,0,turkiston,2025-10-02,2026-09-02,кулон; кулон,51.0,0
4,1979-01-10,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,...,нет,0,0,0,navoiy,2025-10-02,2026-09-02,кулон,46.0,0

In [31]:
df_copy['количество активных просроченных дней'].value_counts()

0      499
24      64
55      25
85      11
2        6
177      6
146      6
267      6
30       6
31       5
116      4
26       4
25       4
62       3
236      3
57       3
205      3
1        3
404      2
27       2
297      2
358      2
298      1
296      1
270      1
455      1
18       1
366      1
349      1
337      1
348      1
361      1
92       1
382      1
89       1
331      1
58       1
93       1
29       1
15       1
65       1
50       1
4        1
40       1
82       1
32       1
119      1
91       1
19       1
179      1
14       1
183      1
147      1
261      1
467      1
Name: количество активных просроченных дней, dtype: int64

In [32]:
len(df_copy)

702

In [33]:
df_copy['is_bad_client'].value_counts(normalize=True)

0    0.89886
1    0.10114
Name: is_bad_client, dtype: float64

In [34]:
df_copy.columns

Index(['дата рождения', 'пол', 'семейное положение', 'количество иждивенцев',
       'профессия', 'статус клиента', 'зарплата', 'сумма кредита',
       'ежемесячное погашение по графику', 'активные кредиты',
       'первоначальный взнос', 'наличие карты', 'сумма просрочки',
       'количество активных просроченных дней',
       'количество кумулятивной просрочки', 'филиал', 'дата выдачи',
       'дата окончания', 'название продукта', 'возраст', 'is_bad_client'],
      dtype='object')

In [35]:
df_copy['филиал'].value_counts()

turkiston    453
navoiy       243
furqat         6
Name: филиал, dtype: int64

In [36]:
feature_cols = ['возраст', 'пол', 'семейное положение', 'количество иждивенцев',
 'профессия', 'статус клиента', 'зарплата', 'сумма кредита',
 'ежемесячное погашение по графику', 'активные кредиты',
 'первоначальный взнос', 'наличие карты', 'филиал', 'название продукта']

In [37]:
selected = df_copy[feature_cols + ['is_bad_client']].copy()

In [38]:
npl_ratio = selected["is_bad_client"].mean() * 100
print(f"NPL: {npl_ratio:.2f}%")

NPL: 10.11%

In [39]:
selected.head()

,возраст,пол,семейное положение,количество иждивенцев,профессия,статус клиента,зарплата,сумма кредита,ежемесячное погашение по графику,активные кредиты,первоначальный взнос,наличие карты,филиал,название продукта,is_bad_client
0,49.0,female,замужем,2.0,nonvoy,активный,2000000.0,15232757,1269396,2,0,нет,navoiy,кулон,0
1,37.0,female,замужем,1.0,tozalik xodimi,активный,3500000.0,4496189,374682,2,0,нет,turkiston,кулон,0
2,33.0,female,замужем,2.0,bolalar hamshirasi,активный,1500000.0,3566595,297216,1,0,нет,navoiy,кулон,0
3,51.0,male,женат,NaN,taksist,активный,4000000.0,7544792,628732,2,0,нет,turkiston,кулон; кулон,0
4,46.0,male,женат,1.0,katta usta,активный,4000000.0,4608685,384057,1,0,нет,navoiy,кулон,0

In [40]:
selected.isna().sum()

возраст                              9
пол                                  0
семейное положение                   0
количество иждивенцев               64
профессия                            0
статус клиента                       0
зарплата                            16
сумма кредита                        0
ежемесячное погашение по графику     0
активные кредиты                     0
первоначальный взнос                 0
наличие карты                        0
филиал                               0
название продукта                    0
is_bad_client                        0
dtype: int64

In [41]:
mean_a = selected['количество иждивенцев'].mean()
selected['количество иждивенцев'] = selected['количество иждивенцев'].fillna(mean_a)

In [42]:
mean_b = selected['зарплата'].mean()
selected['зарплата'] = selected['зарплата'].fillna(mean_b)

In [43]:
mean_c = selected['возраст'].mean()
selected['возраст'] = selected['возраст'].fillna(mean_c)

In [44]:
selected.isna().sum()

возраст                             0
пол                                 0
семейное положение                  0
количество иждивенцев               0
профессия                           0
статус клиента                      0
зарплата                            0
сумма кредита                       0
ежемесячное погашение по графику    0
активные кредиты                    0
первоначальный взнос                0
наличие карты                       0
филиал                              0
название продукта                   0
is_bad_client                       0
dtype: int64

In [45]:
selected.to_csv("../dataset/toyona_gold_cleaned_mulp_prod.csv", index=False)